[fix] scripts/main/MountSSH: Refactor, readability, quoting, improved logging, flag parsing
[fix] scripts/main/UdevSync: Systemd and udev mount logic, led blinking
[refactor] scripts/main/dotsync: Centralized logging, better template, add ShowConfig()
[add] scripts/main/vmctl: Improved logging
[add] scripts/main/JournalToday: Interactive preview of journals, separate daily logs and special log
[add] scripts/main/RyzenProfile: Support for runit and systemd
[new] scripts/other/Chroot: Setup proper mounts and chroot
[new] scripts/other/FixDesktopSessionFiles: Clean session files
[new] scripts/other/Net: Wrapper around iw, wpa_supplicant for minimal environments
[fix] scripts/other/NowPlaying: Fixed infinite socat spamming json to waybar
[new] scripts/other/Random_mac: Random mac address generator
[new] scripts/other/Sway: Pre-launch sway setup
[new] scripts/other/WaybarCava: Cool cava visualizer in waybar

diff --git a/scripts/main/dotsync b/scripts/main/dotsync
--- a/scripts/main/dotsync
+++ b/scripts/main/dotsync
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
 set -euo pipefail
-IFS=$'\n\t'
 
-CONFIG_FILE="${HOME}/.custom/dotsync/config"
+# Main config file: files and directory mapping
+CONFIG_FILE="${HOME}/.custom/${0##*/}/config"
 
 # command in use to copy stuff
 SYNC_="rsync"
@@ -11,52 +11,45 @@ SYNC_="rsync"
 # LOG=0 ERROR=1 INFO=2 DEBUG=3
 LOG_LEVEL=1
 
-declare -a FILES_TO_COPY=()
-declare -a DIRS_TO_COPY=()
+declare -a COPY_FILES=()
+declare -a COPY_DIRS=()
 
 # ASCII colors
 GREEN="\033[38;2;42;204;126m"
 BLUE="\033[38;2;121;118;214m"
 PURPLE="\033[38;2;233;132;64m"
-YELLOW="\033[38;2;238;209;113m"
 RED="\033[38;2;255;10;10m"
 NC="\033[0m"
 HL="\033[1m"
 
-# Temporary variable
-MSG=""
+function log() {
+    local _type="${1}"; shift
+    local _color="" _t=""
+    local -g info_color="\033[38;2;85;255;126m" \
+        warn_color="\033[38;2;255;170;10m" \
+        error_color="\033[38;2;244;29;31m" \
+        fatal_color="\033[5m\033[38;2;255;0;0m" \
+        other_color="\033[38;2;251;255;208m" \
+        nc="\033[0m"
+    case "${_type}" in
+        info) _color="${info_color}" _t=" *" ;;
+        warn) _color="${warn_color}" _t=" ^" ;;
+        debug) _color="${warn_color}" _t=" @" ;;
+        error) _color="${error_color}" _t=" !" ;;
+        fatal) _color="${fatal_color}" _t=" #" ;;
+        *) _color="${other_color}" _t="" ;;
+    esac
 
-function ERROR() {
-    [[ $LOG_LEVEL -ge 1 ]] && {
-        echo -e "[${HL}${RED}ERROR${NC}]: $@"
-    } || {
-        return 0
-    }
-}
-
-function INFO() {
-    [[ $LOG_LEVEL -ge 2 ]] && {
-        echo -e "[${HL}${GREEN}INFO${NC}]: $@"
-    } || {
-        return 0
-    }
-}
-
-function DEBUG_LOG() {
-    [[ $LOG_LEVEL -ge 3 ]] && {
-        echo -e "[${HL}${YELLOW}DEBUG_LOG${NC}]: $@"
-    } || {
-        return 0
-    }
+    printf "[%b%s%b%s]: %b\n" "${_color}" "${_type}" "${nc}" "${_t}" "${*}"
 }
 
 function ColorPath() {
-    echo "$( sed "s@${HOME}@${BLUE//\\/\\\\}\${HOME}${NC//\\/\\\\}@g" <(printf "%s\n" "${1}") )"
+    sed "s@${HOME}@${BLUE//\\/\\\\}~${NC//\\/\\\\}@g" <(printf "%s\n" "${1}")
 }
 
 function CreateConfig() {
     local config="$1"
-    cat > "${config}" << EOF
+    if cat > "${config}" << EOF
 #!/usr/bin/env bash
 
 GIT_DIR="\${HOME}/repos/Dotfiles"
@@ -67,49 +60,51 @@ USERNAME=""
 REPO_NAME=""
 
 CONF_DIR="\${HOME}/.config"
+C="\${CONF_DIR}"
+H="\${HOME}"
 
-### File to file Copy
-FILES_TO_COPY=(
+### Copy file to file
+COPY_FILES=(
     "/etc/vimrc|\${GIT_DIR}/vim/vimrc"
     "/etc/xdg/nvim/init.vim|\${GIT_DIR}/neovim/init.vim"
-    "\${HOME}/.shell_rc|\${GIT_DIR}/shell/SHELL_RC"
-    "\${HOME}/.bashrc|\${GIT_DIR}/shell/bashrc"
+    "\${H}/.shell_rc|\${GIT_DIR}/shell/SHELL_RC"
+    "\${H}/.bashrc|\${GIT_DIR}/shell/bashrc"
+    "\${C}/qutebrowser/config.py|\${GIT_DIR}/qutebrowser/config.py"
 )
 
-### Directory to Directory Copy
-DIRS_TO_COPY=(
-    "\${HOME}/.bin|\${GIT_DIR}/scripts|1"
-    "\${CONF_DIR}/hypr|\${GIT_DIR}/hyprland|1"
-    "\${CONF_DIR}/sway|\${GIT_DIR}/sway|1"
-    "\${CONF_DIR}/i3|\${GIT_DIR}/i3|1"
-    "\${CONF_DIR}/waybar|\${GIT_DIR}/waybar|1"
-    "\${CONF_DIR}/wofi|\${GIT_DIR}/wofi|1"
-    "\${CONF_DIR}/qutebrowser|\${GIT_DIR}/qutebrowser|1"
-    "\${CONF_DIR}/yazi|\${GIT_DIR}/yazi|1"
-    "\${CONF_DIR}/foot|\${GIT_DIR}/foot|1"
-    "\${CONF_DIR}/kitty|\${GIT_DIR}/kitty|1"
-    "\${CONF_DIR}/alacritty|\${GIT_DIR}/alacritty|1"
+### Copy directory to destination (repo) dir
+COPY_DIRS=(
+    "\${H}/.bin|\${GIT_DIR}/scripts|1"
+    "\${C}/hypr|\${GIT_DIR}/hyprland|1"
+    "\${C}/sway|\${GIT_DIR}/sway|1"
+    "\${C}/i3|\${GIT_DIR}/i3|1"
+    "\${C}/waybar|\${GIT_DIR}/waybar|1"
+    "\${C}/wofi|\${GIT_DIR}/wofi|1"
+    "\${C}/yazi|\${GIT_DIR}/yazi|1"
+    "\${C}/foot|\${GIT_DIR}/foot|1"
+    "\${C}/kitty|\${GIT_DIR}/kitty|1"
+    "\${C}/alacritty|\${GIT_DIR}/alacritty|1"
 )
 
-# vim:filetype=bash
+# vim:filetype=iss
 
 EOF
-    if [[ $? -eq 0 ]]; then
-        INFO "Created: '$(ColorPath "${config_file}")'"
+    then
+        log info "Created: '$(ColorPath "${config_file}")'"
     else
-        ERROR "Creating '$(ColorPath "${config_file}")'"
+        log error "Creating '$(ColorPath "${config_file}")'"
         return 1
     fi
     return 0
 }
 
 function ValidatePaths() {
-    local -n indexed_array="$1"
+    local -n indexed_array=${1}
     local valid=0
     for pair in "${indexed_array[@]}"; do
         IFS=$'|' read -r src dest <<< "${pair}"
         if [[ ! -e "${src}" ]]; then
-            ERROR "Invalid file path: $src"
+            log error "Invalid file path: $src"
             valid=1
         fi
     done
@@ -117,15 +112,15 @@ function ValidatePaths() {
 }
 
 function ValidateDirPaths() {
-    local -n indexed_array="$1"
+    local -n indexed_array=${1}
     local valid=0
     for pair in "${indexed_array[@]}"; do
         IFS=$'|' read -r src dest recursive_flag <<< "${pair}"
         if [[ ! -e "${src}" ]]; then
-            ERROR "Invalid directory path: ${src}"
+            log error "Invalid directory path: ${src}"
             valid=1
         elif [[ -z $recursive_flag ]]; then
-            ERROR "Recursive flag not given to '$(ColorPath "${pair}")'"
+            log error "Recursive flag not given to '$(ColorPath "${pair}")'"
             valid=1
         fi
     done
@@ -135,9 +130,10 @@ function ValidateDirPaths() {
 function SourceConfig() {
     local config_file="$1"
     if [[ -s "${config_file}" && -f "${config_file}" ]]; then
-        source "${config_file}" || ERROR "Failed to source '${config_file}'"
+        # shellcheck source=/dev/null
+        source "${config_file}" || log error "Failed to source '${config_file}'"
     else
-        ERROR "'$(ColorPath "${config_file}")' not found"
+        log error "'$(ColorPath "${config_file}")' not found"
         CreateConfig "${config_file}"
     fi
     return 0
@@ -151,18 +147,27 @@ function EditConfig() {
     ${EDITOR:-vim} "${config_file}"
 }
 
+function ShowConfig() {
+    local config_file="${CONFIG_FILE}"
+    if command -v bat &> /dev/null; then
+        bat --paging=never --decorations=never --color=always "${config_file}"
+    else
+        cat "${config_file}"
+    fi
+}
+
 function CopyFiles() {
     local src_="$1"
     local dest_="$2"
     local -a cmd_flags=()
 
     if [[ ! -f "${src_}" ]]; then
-        ERROR "Source '${BLUE}${src_}${NC}' file does not exist"
+        log error "Source '${BLUE}${src_}${NC}' file does not exist"
         return 1
     fi
 
     if [[ "$SYNC_" != "rsync" ]]; then
-        ERROR "Deletion of orphanes requires 'rsync'. Current: '$SYNC_'"
+        log error "Deletion of orphanes requires 'rsync'. Current: '$SYNC_'"
         return 1
     fi
 
@@ -178,9 +183,9 @@ function CopyFiles() {
     fi
 
     if $SYNC_ "${cmd_flags[@]}" "${src_}" "${dest_}"; then
-        INFO "Copied '${GREEN}$(ColorPath ${src_})${NC}' ${PURPLE}--->${NC} '${BLUE}$(ColorPath ${dest_})${NC}'"
+        log info "Copied '${GREEN}$(ColorPath "${src_}")${NC}' ${PURPLE}--->${NC} '${BLUE}$(ColorPath "${dest_}")${NC}'"
     else
-        ERROR "Copy Failed: ${src_} --> ${dest_}"
+        log error "Copy Failed: ${src_} --> ${dest_}"
     fi
 }
 
@@ -191,12 +196,12 @@ function CopyDirs() {
     local -a cmd_flags=()
 
     if [[ ! -d "${src_}" ]]; then
-        ERROR "Source '${BLUE}${src_}${NC}' directory does not exist"
+        log error "Source '${BLUE}${src_}${NC}' directory does not exist"
         return 1
     fi
 
     if [[ "$SYNC_" != "rsync" && $delete_flag -eq 1 ]]; then
-        ERROR "Deletion of orphanes requires 'rsync'. Current: '$SYNC_'"
+        log error "Deletion of orphanes requires 'rsync'. Current: '$SYNC_'"
         return 1
     fi
 
@@ -212,9 +217,9 @@ function CopyDirs() {
     fi
 
     if $SYNC_ "${cmd_flags[@]}"  "${src_}/" "${dest_}/"; then
-        INFO "Copied '${GREEN}$(ColorPath ${src_})${NC}' ${PURPLE}--->${NC} '${BLUE}$(ColorPath ${dest_})${NC}'"
+        log info "Copied '${GREEN}$(ColorPath "${src_}")${NC}' ${PURPLE}--->${NC} '${BLUE}$(ColorPath "${dest_}")${NC}'"
     else
-        ERROR "Copy Failed: ${src_} --> ${dest_}"
+        log error "Copy Failed: ${src_} --> ${dest_}"
     fi
 }
 
@@ -222,21 +227,21 @@ function CloneRepo() {
     local DIR="$1"
 
     [[ -z "${USERNAME}" && -z "${REPO_NAME}" ]] && {
-        ERROR "No github username or repo name is given"
+        log error "No github username or repo name is given"
         exit 1
     }
 
     if [[ -z "${DIR}" ]]; then
-        INFO "No directory given. Using your current directory to clone"
+        log info "No directory given. Using your current directory to clone"
         DIR="$(realpath .)/${REPO_NAME}"
     else
-        DIR="$(realpath $1)/${REPO_NAME}"
+        DIR="$(realpath "$1")/${REPO_NAME}"
     fi
 
-    DEBUG_LOG "Getting dotfile repo from github"
-    INFO "Cloning your repository at: $DIR"
+    log debug "Getting dotfile repo from github"
+    log info "Cloning your repository at: $DIR"
     git clone "https://github.com/${USERNAME}/${REPO_NAME}.git" "${DIR}" && \
-        INFO "Repository clone at '${BLUE}$(ColorPath ${DIR})${NC}'"
+        log info "Repository clone at '${BLUE}$(ColorPath "${DIR}")${NC}'"
 }
 
 function PushToRepo() {
@@ -253,24 +258,24 @@ function PushToRepo() {
     [[ -z "${commit_template_file}" ]] && commit_template_file=<( printf "[tag] module: what changed\n\n" )
 
     if [[ -z "${USERNAME}" ]]; then
-        ERROR "'USERNAME' is empty update your '$(ColorPath "${CONFIG_FILE}")'"
+        log error "'USERNAME' is empty update your '$(ColorPath "${CONFIG_FILE}")'"
         return 1
     fi
     if [[ -z "${REPO_NAME}" ]]; then
-        ERROR "'REPO_NAME' is empty update your '$(ColorPath "${CONFIG_FILE}")'"
+        log error "'REPO_NAME' is empty update your '$(ColorPath "${CONFIG_FILE}")'"
         return 1
     fi
 
     cd "${GIT_DIR}"
 
     if ! git diff --quiet ; then
-        INFO "Launching git interactive git add"
+        log info "Launching git interactive git add"
         git add -p || {
-            ERROR "Interactive staging failed"
+            log error "Interactive staging failed"
             return 1
         }
     fi
-    INFO "Summary of staged changes"
+    log info "Summary of staged changes"
     git diff --staged --stat
 
     printf "%s: " "Are you saisfied with changes? (y|n)"; read -r satisfied
@@ -279,29 +284,29 @@ function PushToRepo() {
         printf "%s: " "Commit? (y|n)"; read -r should_commit
         [[ "${should_commit}" =~ ^(y|yes|Yes)$ ]] || return 1
         if git commit --template="${commit_template_file}"; then
-            INFO "Successfully commited the changes"
+            log info "Successfully commited the changes"
         else
              if ! git diff --quiet --staged && git diff --quiet --staged; then
-                 ERROR "Commit failed" && exit 1
+                 log error "Commit failed" && exit 1
              fi
         fi
     else
-        INFO "Commit aborted"
+        log info "Commit aborted"
         printf "%s: " "Continue to commit?"; read -r should_continue
         [[ "${should_continue}" =~ ^(y|yes|Yes)$ ]] || exit 1
     fi
-    INFO "Pushing changes to git@github.com:${USERNAME}/${REPO_NAME}.git"
-    git push "git@github.com:${USERNAME}/${REPO_NAME}.git" $(git symbolic-ref --short HEAD) ${force} && \
-        INFO "Successfully pushed your changes to github repository"
+    log info "Pushing changes to git@github.com:${USERNAME}/${REPO_NAME}.git"
+    git push "git@github.com:${USERNAME}/${REPO_NAME}.git" "$(git symbolic-ref --short HEAD)" "${force}" && \
+        log info "Successfully pushed your changes to github repository"
 }
 
 function Cleanup() {
-    ERROR "${RED}Sync interrupted. Clean up manually.${NC}" && exit 1
+    log error "${RED}Interrupted, Clean up manually.${NC}" && exit 1
 }
 
 function Usage() {
     printf "%b\n" \
-    "${HL}Backup - Your Dotfiles Backup and Sync Script${NC}" \
+    "${HL}Sync and Backup dotfile${NC}" \
     "" \
     "Usage:" \
     "  BackUp [options]" \
@@ -311,7 +316,8 @@ function Usage() {
     "  -v, --verbose         Set verbose output (LOG_LEVEL=1)" \
     "  -l=N, --log=N         Set log level (0=none, 1=error, 2=info, 3=debug)" \
     "  -d, --debug           Enable debug level logging (LOG_LEVEL=3)" \
-    "  -e, --edit            Edit the config file" \
+    "  -e, --edit            Edit the config file ($(ColorPath "${CONFIG_FILE}"))" \
+    "  -s, --show            Show the config file ($(ColorPath "${CONFIG_FILE}"))" \
     "  -g, --git-status      Show git status of your dotfile repo after backup" \
     "  -c DIR, --clone DIR   Clone your dotfile repo to specified DIR (local path)" \
     "  -m MSG, --msg MSG     Commit message for git push" \
@@ -319,11 +325,11 @@ function Usage() {
     "  --force               Force git push with --force flag" \
     ""  \
     "Description:" \
-    "  This script copies your important config files and directories into a" \
-    "  local git repository (${BLUE}${GIT_DIR}${NC}) for backup and version control." \
-    "  You can optionally clone your dotfiles repo, push changes, and see git status." \
+    "  This script copies important config files and directories into a" \
+    "  local git repository (${BLUE}$(ColorPath "${GIT_DIR}")${NC}) for backup and version control." \
+    "  Optionally can clone your dotfiles repo from remote, push changes, and see git status." \
     "" \
-    "GitHub repo info:" \
+    "Your Remote repo info:" \
     "  Username: ${BLUE}${USERNAME}${NC}" \
     "  Repository: ${BLUE}${REPO_NAME}${NC}"
 }
@@ -334,33 +340,36 @@ function main() {
     # An array to hold all the given flags
     local -a flagArr=("$@")
 
+    # Temporary variable
+    local -g MSG=""
+
     # 1 for git status 0 for no git status
     local git_status=0
 
     # Toggle push or pull
-    local should_push=0
-    local should_clone=0
+    local -i should_push=0 should_clone=0
+    local -i show_help=0 show_config=0
     # Clone directory
     local clone_dir=""
 
     # string '--force'
     local force=""
 
-    for (( i=0 ; i < ${#flagArr[@]} ; i++ )); do
+    for ((i=0;i<${#flagArr[@]};i++)); do
         arg="${flagArr[$i]}"
         case "${arg}" in
             -v|-*verbose|-*progress|verbose)
                 LOG_LEVEL=1
-                DEBUG_LOG "Verbose is set"
+                log debug "Verbose is set"
                 ;;
             -l=*|-*log*=*|log*=*)
                 LOG_LEVEL=${arg#*=}
                 if [[ -z ${LOG_LEVEL} || ${LOG_LEVEL} == -* ]] || [[ ! ${LOG_LEVEL} =~ ^[0-9]+$ ]]; then
                     LOG_LEVEL=1
                 elif [[ $LOG_LEVEL -gt 3 ]]; then
-                    DEBUG_LOG "LOG_LEVEL has no effect over integer ${LOG_LEVEL}"
+                    log debug "LOG_LEVEL has no effect over integer ${LOG_LEVEL}"
                 fi
-                [[ $LOG_LEVEL -ge 3 ]] && DEBUG_LOG "Debugging enabled"
+                [[ $LOG_LEVEL -ge 3 ]] && log debug "Debugging enabled"
                 ;;
             -l|-*log*|log*)
                 LOG_LEVEL=${flagArr[$(( i + 1 ))]:-1}
@@ -368,22 +377,25 @@ function main() {
                 if [[ -z ${LOG_LEVEL} || ${LOG_LEVEL} == -* ]]; then
                     LOG_LEVEL=1
                 elif [[ $LOG_LEVEL -gt 3 ]]; then
-                    DEBUG_LOG "LOG_LEVEL has no effect over integer ${LOG_LEVEL}"
+                    log debug "LOG_LEVEL has no effect over integer ${LOG_LEVEL}"
                 fi
-                [[ $LOG_LEVEL -ge 3 ]] && DEBUG_LOG "Debugging enabled"
+                [[ $LOG_LEVEL -ge 3 ]] && log debug "Debugging enabled"
                 i=$(( i + 1 ))
                 ;;
             -d-*debug|debug)
                 LOG_LEVEL=2
-                DEBUG_LOG "Debugging enabled"
+                log debug "Debugging enabled"
                 ;;
             -g|-*gs|-*git*stat*|git*stat*)
                 git_status=1
-                DEBUG_LOG "git_status is set"
+                log debug "git_status is set"
                 ;;
             -e|-*edit|edit)
                 EditConfig "${CONFIG_FILE}"
                 return 0
+                ;;
+            -s|-*show|show)
+                show_config=1
                 ;;
             -c|--clone*|clone*)
                 clone_dir="${flagArr[$(( i + 1 ))]}"
@@ -406,26 +418,26 @@ function main() {
             -p|-*push|push)
                 should_push=1
                 LOG_LEVEL=2
-                DEBUG_LOG "Backup will be pushed to github"
+                log debug "Backup will be pushed to github"
                 ;;
             -*force)
                 force="--force"
-                DEBUG_LOG "Forcing push"
+                log debug "Forcing push"
                 ;;
-            -h|-*help|help)
-                Usage
-                return 0
-                ;;
+            -h|-*help|help) show_help=1 ;;
             *)
-                ERROR "Invalid flag: $arg"
+                log error "Invalid flag: $arg"
                 ;;
         esac
     done
 
     SourceConfig "${CONFIG_FILE}"
 
-    ValidatePaths "FILES_TO_COPY" || return 1
-    ValidateDirPaths "DIRS_TO_COPY" || return 1
+    [[ $show_help -eq 1 ]] && { Usage; return 0; }
+    [[ $show_config -eq 1 ]] && { ShowConfig; return 0; }
+
+    ValidatePaths COPY_FILES || return 1
+    ValidateDirPaths COPY_DIRS || return 1
 
     if [[ "${should_clone}" -eq 1 ]]; then
         CloneRepo "${clone_dir}"
@@ -434,50 +446,49 @@ function main() {
 
     if command -v rsync 1> /dev/null 2>&1; then
         SYNC_="rsync"
-        [[ $? -ne 0 ]] && ERROR "'rsync' not found. Falling back to 'cp'."
     elif command -v cp 1> /dev/null 2>&1; then
         SYNC_="cp"
     fi
 
     # Why local dotfile directory doesn't exist
     if [[ ! -d "${GIT_DIR}" ]]; then
-        INFO "$(ColorPath ${GIT_DIR}) doesn't exist"
-        mkdir --parents "${GIT_DIR}" && {
-            INFO "Created $(ColorPath ${GIT_DIR})"
-        } || {
-            ERROR "Cannot create '${BLUE}${GIT_DIR}${NC}'"
+        log info "$(ColorPath "${GIT_DIR}") doesn't exist"
+        if mkdir --parents "${GIT_DIR}"; then
+            log info "Created $(ColorPath "${GIT_DIR}")"
+        else
+            log error "Cannot create '${BLUE}${GIT_DIR}${NC}'"
             return 1
-        }
+        fi
     fi
 
-    DEBUG_LOG "Using GIT_DIR=$(ColorPath ${GIT_DIR})"
-    DEBUG_LOG "Using git_status=$git_status"
-    DEBUG_LOG "Using LOG_LEVEL=$LOG_LEVEL"
-    DEBUG_LOG "Using SYNC_=$SYNC_"
+    log debug "Using GIT_DIR=$(ColorPath "${GIT_DIR}")"
+    log debug "Using git_status=$git_status"
+    log debug "Using LOG_LEVEL=$LOG_LEVEL"
+    log debug "Using SYNC_=$SYNC_"
 
     # Start copying all the files to the destination
-    for pair in "${FILES_TO_COPY[@]}"; do
+    for pair in "${COPY_FILES[@]}"; do
         IFS=$'|' read -r src dest <<< "${pair}"
         CopyFiles "${src}" "${dest}"
     done
 
     # Start copying directory content with selective deletion
-    for dir_spec in "${DIRS_TO_COPY[@]}"; do
+    for dir_spec in "${COPY_DIRS[@]}"; do
         IFS=$'|' read -r src dest delete_flag <<< "${dir_spec}"
         CopyDirs "${src}" "${dest}" "${delete_flag}"
     done
 
     if [[ ${git_status} -eq 1 ]]; then
         printf '\n\n'
-        cd ${GIT_DIR}
+        cd "${GIT_DIR}"
         if git status &> /dev/null; then
             git status
         else
-            ERROR "Not a git repository"
+            log error "Not a git repository"
         fi
     fi
 
-    echo && INFO "Dotfile directory: ${BLUE}$(ColorPath ${GIT_DIR})${NC}\n"
+    printf '\n' && log info "Dotfile directory: ${BLUE}$(ColorPath "${GIT_DIR}")${NC}\n"
 
     if [[ $should_push -eq 1 ]]; then
         PushToRepo "${force}" || return 1
diff --git a/scripts/main/vmctl b/scripts/main/vmctl
--- a/scripts/main/vmctl
+++ b/scripts/main/vmctl
@@ -2,39 +2,39 @@
 
 set -euo pipefail
 
-# Colors
+# Global Colors
 HL="\033[1m"
 NC="\033[0m"
 MSG_COL="\033[38;2;255;240;200m"
-RED="\033[38;2;196;29;31m"
 BLUE="\033[38;2;116;112;218m"
-WARN_COL="\033[38;2;203;82;96m"
 
-function LOG() {
-    local type_="$1"
-    shift
-    case "${type_}" in
-        info)
-            printf "%b\n" "$*"
-            ;;
-        error)
-            printf "[%b%s%b]: %b\n" "${RED}"      "ERR"  "${NC}" "$*"
-            ;;
-        warn)
-            printf "[%b%s%b]: %b\n" "${WARN_COL}" "WARN" "${NC}" "$*"
-            ;;
-        fatal)
-            printf "[%b%s%b]: %b\n" "${RED}"      "FATAL" "${NC}" "$*"
-            exit 1
-            ;;
+# Log function
+function log() {
+    local _type="${1}"; shift
+    local _color="" _t=""
+    local -g info_color="\033[38;2;85;255;126m" \
+        warn_color="\033[38;2;255;170;10m" \
+        error_color="\033[38;2;244;29;31m" \
+        fatal_color="\033[5m\033[38;2;255;0;0m" \
+        other_color="\033[38;2;251;255;208m" \
+        nc="\033[0m"
+    case "${_type}" in
+        info) _color="${info_color}" _t="*" ;;
+        warn) _color="${warn_color}" _t="^" ;;
+        error) _color="${error_color}" _t="!" ;;
+        fatal) _color="${fatal_color}" _t="#" ;;
+        *) _color="${other_color}" _t="" ;;
     esac
+
+    printf "[%b%s%b%s]: %b\n" "${_color}" "${_type}" "${nc}" "${_t}" "${*}"
 }
+
 
 # Usage message
 function Usage() {
-    local config_file="$1"
-    local script_basename="$(basename "$0")"
-    printf '\n%b\n' "${HL}Usage${NC}: $(basename "$0") [boot] [options] <profile1> <profile2> ...\n"
+    local config_file="${1}"
+    local script_basename="${0##*/}"
+    printf '\n%b\n' "${HL}Usage${NC}: ${script_basename} [boot] [options] <profile1> <profile2> ...\n"
     printf "  ${MSG_COL}%-18b${NC} %b\n" \
         "boot"              "Boot from ISO + disk image" \
         "<profile>"         "Profile name (defined in $(ColorPath "${config_file}"))" \
@@ -67,9 +67,18 @@ function load_profile() {
     local -n selected_profile=${profile_name}
 
     if ! declare -p "${profile_name}" 2> /dev/null | grep -q 'declare -a' ; then
-        LOG fatal "Profile '${profile_name}' not found."
+        log fatal "Profile '${profile_name}' not found."
+        return 1
     fi
 
+    for n in "${selected_profile[@]}"; do
+        [[ "${n}" != *=* ]] && { log error "invalid pair '${n}'"; return 1; }
+        IFS=$'=' read -r key value "${n}"
+        case "${key}" in
+            img) disk_img_+=("${value}") ;;
+            iso) iso_img_="${value}" ;;
+        esac
+    done
     disk_img_="${selected_profile[0]}"
     iso_img_="${selected_profile[1]:="No_ISO"}"
     disk_format_="${disk_img_##*.}"
@@ -81,14 +90,14 @@ function EditConfigFile() {
 }
 
 function ColorPath() {
-    echo "$( sed "s@${HOME}@${BLUE//\\/\\\\}\${HOME}${NC//\\/\\\\}@g" <(printf "%s\n" "${1}") )"
+    sed "s@${HOME}@${BLUE//\\/\\\\}~${NC//\\/\\\\}@g" <(printf "%s\n" "${1}")
 }
 
 function ListProfiles() {
     local config_file="$1"
     local -a available_profiles=""
     [[ -f "${config_file}" ]] || return 1
-    LOG info "Available profiles in $(ColorPath "${config_dir}"):"
+    log info "Available profiles in $(ColorPath "${config_dir}"):"
     mapfile -t available_profiles < <(grep -o '^[A-Za-z_]*=(' "${config_file}" | sed 's/=(//')
     for (( i=0; i < ${#available_profiles[@]}; i++ )); do
         printf '   %s. %b\n' "$((i+1))" "${available_profiles[$i]}"
@@ -101,33 +110,30 @@ function CreateDiskImg() {
     local size="$3"
     [[ "${img}" == *.* ]] || img="${img}.${format}"
     qemu-img create -f ${format:-"raw"} "${img}" "${size:-"20G"}"
-    LOG info "Disk created:"
+    log info "Disk created:"
     printf '    %s %-4s = %s\n' \
         "Disk image:  "  ""  "${img}" \
         "Disk size:   "  ""  "${size:-"20G"}" \
         "Disk format: "  ""  "${format:-"raw"}"
 }
 
-function WriteToProfile() {
-    local config_file="$1"
+function WriteProfile() {
+    local config_file="${1}"
     local profile_name="${2:-"default"}"
     local img="${3:-""}"
     local iso="${4:-""}"
-    local comment="$5"
-    msg="${profile_name^}"
-    if [[ -n "${comment}" ]];then
-        msg+=": ${comment^}"
-    fi
-
+    local comment="${5:-""}"
+    local msg="${profile_name^}"
+    [[ -n "${comment}" ]] && msg+=": ${comment^}"
     mapfile -t available_profiles < <(grep -o '^[A-Za-z_]*=(' "${config_file}" | sed 's/=(//')
-    for (( i=0; i < ${#available_profiles[@]}; i++ )); do
+    for ((i=0;i<${#available_profiles[@]};i++)); do
         if [[ "${profile_name}" == "${available_profiles[$i]}" ]]; then
             return 1
         fi
     done
 
-    [[ -s "${config_file}" ]] || echo '#!/usr/bin/env bash' > "${config_file}"
-    cat >> "${config_file}" << EOF
+    [[ -s "${config_file}" ]] || printf '%s\n' '#!/usr/bin/env bash' 1> "${config_file}"
+    if cat >> "${config_file}" << EOF
 
 # ${msg}
 ${profile_name}=(
@@ -139,8 +145,10 @@ ${profile_name}=(
 )
 
 EOF
-    if [[ $? -eq 0 ]]; then
-        LOG info "New profile added: Profile: '${profile_name}'"
+    then
+        log info "New profile added: Profile: '${profile_name}'"
+    else
+        log info "Failed to add profile: Profile: '${profile_name}'"
     fi
     return 0
 }
@@ -148,7 +156,7 @@ EOF
 function print_row() {
     local label="$1"
     local value="$2"
-    printf "  %b%-16b%b: %b\n" "$MSG_COL" "$label" "$NC" "$value"
+    printf "  %b%-16b%b: %b\n" "$MSG_COL" "$label" "${NC}" "$value"
 }
 
 # Boot VM with ISO
@@ -251,141 +259,72 @@ function main() {
     if [[ -s "${config_file}" && -f "${config_file}" ]]; then
         source "${config_file}"
     else
-        LOG warn "No profile found. Creating a default"
-        if WriteToProfile "${config_file}"; then
-            LOG info "New default profile created at '$(ColorPath "${config_file}")'"
+        log warn "No profile found. Creating a default"
+        if WriteProfile "${config_file}"; then
+            log info "New default profile created at '$(ColorPath "${config_file}")'"
         fi
     fi
 
+    set_value() {
+        local -n var_ref=${1}
+        local -n value_ref=${2}
+        [[ -n "${value_ref}" ]] || { log error "'${var_ref}' requires a value"; return 1; }
+        var_ref="${value_ref}"
+    }
+
     # Parse args
-    for (( i=0; i < ${#arg_array[@]}; i++ )); do
-        arg="${arg_array[$i]}"
+    for arg in "${arg_array[@]}"; do
+        if [[ "${arg}" == *=* ]]; then
+            IFS=$'=' read -r arg value <<< "${arg}"
+            [[ -n "${value}" ]] || { log error "'${arg}' requires a value"; return 1; }
+        fi
         case "${arg}" in
-            boot|-*boot)
-                boot=1
-                ;;
-            im*g*=*|-*im*g*=*)
-                disk_img="${arg#*=}"
-                ;;
-            iso*=*|-*iso*=*)
-                iso_img="${arg#*=}"
-                ;;
-            ram=*|-*ram=*)
-                ram="${arg#*=}"
-                ;;
-            im*g*|-*im*g*)
-                disk_img="${arg_array[$((i+1))]}"
-                ;;
-            iso*|-*iso*)
-                iso_img="${arg_array[$((i+1))]}"
-                ;;
-            ram|-*ram)
-                ram="${arg_array[$((i+1))]}"
-                ;;
-            create*im*=*|-*create*im*=*)
-                create_img="${arg#*=}"
-                if [[ -n "${create_img}" ]]; then
-                    should_create_img=1
-                else
-                    LOG fatal "No image specified"
-                fi
-                local next_arg="${arg_array[$((i+1))]}"
-                case "$next_arg" in
-                    raw|qcow2)
-                        disk_format="$next_arg"
-                        i=$((i+1))
-                        ;;
-                esac
-                if [[ -n "${create_img#*.}" && -z "${disk_format}" ]]; then
-                    disk_format="${create_img#*.}"
-                else
-                    disk_format="${disk_format}"
-                fi
-                next_arg="${arg_array[$((i+1))]}"
-                if [[ "${next_arg}" =~ ^[0-8]+(K|M|G)$ ]]; then
-                    disk_size="${next_arg}"
-                    i=$((i+1))
-                fi
-                unset next_arg
-                ;;
+            boot|-*boot) boot=1 ;;
+            image|-*image) set_value disk_img value ;;
+            iso|-*iso) set_value iso_img value ;;
+            ram|-*ram) set_value ram value ;;
+            comm*) set_value comment value ;;
+            for*) set_value disk_format value ;;
+            pro*|-*pro*) set_value profile_name value ;;
+            -f|-*full*|*full*) full_scr=1 ;;
+            -*l|list*|-*list*) ListProfiles "${config_file}" return 0 ;;
+            edit|-*edit) EditConfigFile "${config_file}" return 0 ;;
+            h|-h|-*help|help) Usage "${config_file}" return 0 ;;
             create*im*|-*create*im*)
-                create_img="${arg_array[$((i+1))]}"
-                if [[ -n "${create_img}" ]]; then
-                    should_create_img=1
-                    i=$((i+1))
-                else
-                    LOG fatal "No image specified"
-                fi
-                local next_arg="${arg_array[$((i+1))]}"
-                case "${next_arg}" in
-                    raw|qcow2)
-                        disk_format="${next_arg}"
-                        i=$((i+1))
-                        ;;
+                IFS=$',' read -r create_img disk_format disk_size <<< "${value}"
+
+                # Image file
+                [[ -n "${create_img}" ]] && should_create_img=1 || { log fatal "No image specified"; return 1; }
+
+                # Disk format
+                case "${disk_format}" in
+                    raw|qcow2) set_value disk_format value ;;
+                    *) log error "Unknown format" ;;
                 esac
-                if [[ -z "${disk_format}" ]]; then
-                    disk_format="${create_img#*.}"
-                else
-                    disk_format="${disk_format}"
+
+                if [[ -z "${disk_format}" ]]; then disk_format="${create_img##*.}"
+                else disk_format="${disk_format}"
                 fi
-                next_arg="${arg_array[$((i+1))]}"
-                if [[ "${next_arg}" =~ ^[0-8]+(K|M|G)$ ]]; then
-                    disk_size="${next_arg}"
-                    i=$((i+1))
+
+                # Disk size
+                if [[ "${disk_size}" =~ ^[0-8]+(K|M|G)$ ]]; then
+                    disk_size="${disk_size}"
                 fi
-                unset next_arg
-                ;;
-            new*pro=*|create*pro=*|pro*=*|-*create*pro*=*|-*new*pro*=*)
-                profile_name="${arg#*=}"
-                [[ -z "${profile_name}" ]] && LOG fatal "No profile specified"
-                should_create_profile=1
                 ;;
             new*pro*|create*pro*|pro*|-*create*pro*|-*new*pro*)
-                profile_name="${arg_array[$((i+1))]}"
-                [[ -z "${profile_name}" ]] && LOG fatal "No profile specified"
+                set_value profile_name value
+                [[ -z "${profile_name}" ]] && log fatal "No profile specified"
                 should_create_profile=1
-                i=$((i+1))
-                ;;
-            comm*)
-                comment="${arg}"
-                ;;
-            comm*=*)
-                comment="${arg_array[$((i+1))]}"
-                ;;
-            for*)
-                disk_format="${arg_array[$((i+1))]}"
-                ;;
-            pro*=*|-*pro*=*)
-                profile_name="${arg#*=}"
-                ;;
-            pro*|-*pro*)
-                profile_name="${arg_array[$((i+1))]}"
-                i=$((i+1))
-                ;;
-            f|-f|-*full*|*full*)
-                full_scr=1
-                ;;
-            -*l|list*|-*list*)
-                ListProfiles "${config_file}"
-                return 0
-                ;;
-            edit|-*edit)
-                EditConfigFile "${config_file}"
-                return 0
-                ;;
-            h|-h|-*help|help)
-                Usage "${config_file}"
-                return 0
                 ;;
             [A-Za-z_]*)
                 if declare -p "${arg}" 2> /dev/null | grep -q 'declare -a'; then
                     requested_profiles+=("${arg}")
                 else
-                    LOG fatal "'${arg}' Not a valid profile"
+                    log fatal "'${arg}' Not a valid profile"
                 fi
                 ;;
             *)
-                LOG warn "Unknown argument: '${arg}'"
+                log warn "Unknown argument: '${arg}'"
                 Usage "${config_file}"
                 return 1
                 ;;
@@ -397,19 +336,19 @@ function main() {
     fi
 
     if [[ $should_create_img -eq 1 ]]; then
-        [[ -z "${profile_name}" ]] && LOG fatal "No profile name specified"
-        [[ -z "${create_img}" ]] && LOG fatal "No disk image specified"
-        [[ -z "${disk_format}" ]] &&  LOG fatal "No disk format specified"
-        [[ -z "${disk_size}" || "${disk_size}" == "0" ]] && LOG fatal "No image size specified"
+        [[ -z "${profile_name}" ]] && log fatal "No profile name specified"
+        [[ -z "${create_img}" ]] && log fatal "No disk image specified"
+        [[ -z "${disk_format}" ]] &&  log fatal "No disk format specified"
+        [[ -z "${disk_size}" || "${disk_size}" == "0" ]] && log fatal "No image size specified"
         mkdir -p "${config_dir}/${profile_name}"
         CreateDiskImg "${config_dir}/${profile_name}/${create_img}" "${disk_format}" "${disk_size}"
-        [[ $? -eq 0 ]] && return 0 || return 1
+        return 0
     fi
 
     if [[ $should_create_profile -eq 1 ]]; then
         local temp_iso_img="" temp_create_img=""
         if [[ -z "${iso_img}" ]]; then
-            LOG warn "No ISO image is given"
+            log warn "No ISO image is given"
             temp_iso_img=""
         elif [[ "${iso_img}" != */* ]]; then
             temp_iso_img="${config_dir}/${profile_name}/${iso_img}"
@@ -418,7 +357,7 @@ function main() {
         fi
 
         if [[ -z "${disk_img}" ]]; then
-            LOG fatal "No disk image is given"
+            log fatal "No disk image is given"
         elif [[ "${disk_img}" != */* ]]; then
             temp_iso_img="${config_dir}/${profile_name}/${disk_img}"
         else
@@ -429,13 +368,13 @@ function main() {
             temp_create_img="${config_dir}/${profile_name}/${create_img}"
         fi
 
-        WriteToProfile "${config_file}" "${profile_name}" "${disk_img:-"${temp_create_img}"}" "${iso_img:-"${temp_iso_img}"}" "${comment}" || \
-            LOG warn "'${profile_name}' already exists"
+        WriteProfile "${config_file}" "${profile_name}" "${disk_img:-"${temp_create_img}"}" "${iso_img:-"${temp_iso_img}"}" "${comment}" || \
+            log warn "'${profile_name}' already exists"
         [[ $? -eq 0 ]] && return 0 || return 1
     fi
 
     if [[ ${#requested_profiles[@]} -eq 0 ]]; then
-        [[ -n "${profile_name}" ]] || LOG fatal "No profile name was given"
+        [[ -n "${profile_name}" ]] || log fatal "No profile name was given"
     fi
 
     source "${config_file}"
@@ -452,17 +391,17 @@ function main() {
 
         # Path checks for disk image
         if [[ -z "${disk_img}" ]]; then
-            LOG fatal "No disk image given"
+            log fatal "No disk image given"
         elif [[ ! -s "${disk_img}" || ! -f "${disk_img}" ]]; then
-            LOG fatal "Disk image '${BLUE}${disk_img}${NC}' does not exist; Update it\n"
+            log fatal "Disk image '${BLUE}${disk_img}${NC}' does not exist; Update it\n"
         fi
 
         if [[ $boot -eq 1 ]]; then
             # Path checks for iso image
             if [[ -z "${iso_img}" ]]; then
-                LOG fatal "No ISO image given"
+                log fatal "No ISO image given"
             elif [[ ! -s "${iso_img}" || ! -f "${iso_img}" ]]; then
-                LOG fatal "ISO '${BLUE}${iso_img}${NC}' does not exist"
+                log fatal "ISO '${BLUE}${iso_img}${NC}' does not exist"
             fi
         fi
 
