[feature] scripts/main/RyzenProfile: Add hot reload, add -status flag, show ps output, [active|stale] diff etc.
[refactor] <others>: REFACTORED, FIXED SHELLCHECK WARNINGS AND INFO ETC.

diff --git a/scripts/main/Dotsync b/scripts/main/Dotsync
--- a/scripts/main/Dotsync
+++ b/scripts/main/Dotsync
@@ -54,9 +54,9 @@ function CreateConfig() {
 
 GIT_DIR="\${HOME}/repos/Dotfiles"
 
-# Your GitHub username
-USERNAME=""
-# Your GitHub repository
+# Your Remote username
+REMOTE_USERNAME=""
+# Your Remote repository name
 REPO_NAME=""
 
 CONF_DIR="\${HOME}/.config"
@@ -74,9 +74,10 @@ COPY_FILES=(
 
 ### Copy directory to destination (repo) dir
 COPY_DIRS=(
+    #    src   |    dest   | [1|0] (1 = delete files from dest if not in src, 0 = do nothing)
     "\${H}/.bin|\${GIT_DIR}/scripts|1"
-    "\${C}/hypr|\${GIT_DIR}/hyprland|1"
     "\${C}/sway|\${GIT_DIR}/sway|1"
+    "\${C}/hypr|\${GIT_DIR}/hyprland|1"
     "\${C}/i3|\${GIT_DIR}/i3|1"
     "\${C}/waybar|\${GIT_DIR}/waybar|1"
     "\${C}/wofi|\${GIT_DIR}/wofi|1"
@@ -90,9 +91,10 @@ COPY_DIRS=(
 
 EOF
     then
-        log info "Created: '$(ColorPath "${config_file}")'"
+        log info "New configuration generated (with defaults): '$(ColorPath "${config_file}")'"
+        log info "Edit it accordingly, To edit configuration use '${0##*/} --edit'"
     else
-        log error "Error creating '$(ColorPath "${config_file}")'"
+        log error "Error creating configuration: '$(ColorPath "${config_file}")'"
         return 1
     fi
     return 0
@@ -100,7 +102,7 @@ EOF
 
 function ValidatePaths() {
     local -n indexed_array=${1}
-    local valid=0
+    local -i valid=0
     for pair in "${indexed_array[@]}"; do
         IFS=$'|' read -r src dest <<< "${pair}"
         if [[ ! -e "${src}" ]]; then
@@ -113,31 +115,32 @@ function ValidatePaths() {
 
 function ValidateDirPaths() {
     local -n indexed_array=${1}
-    local valid=0
+    local -i is_valid=0
     for pair in "${indexed_array[@]}"; do
         IFS=$'|' read -r src dest recursive_flag <<< "${pair}"
         if [[ ! -e "${src}" ]]; then
             log error "Invalid directory path: ${src}"
-            valid=1
-        elif [[ -z $recursive_flag ]]; then
+            is_valid=$((is_valid+1))
+        fi
+        if [[ -z "${dest}" ]]; then
+            log error "dest cannot be empty: ${src}"
+            is_valid=$((is_valid+1))
+        fi
+        if [[ -z $recursive_flag ]]; then
             log error "Recursive flag not given to '$(ColorPath "${pair}")'"
-            valid=1
+            is_valid=$((is_valid+1))
         fi
     done
-    return $valid
+    return $is_valid
 }
 
 function SourceConfig() {
     local config_file="$1"
-    if [[ -s "${config_file}" && -f "${config_file}" ]]; then
-        # shellcheck source=/dev/null
-        source "${config_file}" || log error "Failed to source '${config_file}'"
-    else
-        log error "'$(ColorPath "${config_file}")' not found"
+    if [[ ! -s "${config_file}" || ! -f "${config_file}" ]]; then
         CreateConfig "${config_file}"
-        source "${config_file}" || log error "Failed to source '${config_file}'"
     fi
-    return 0
+    # shellcheck source=/dev/null
+    source "${config_file}" || { log error "Failed to source '${config_file}'"; return 1; }
 }
 
 function EditConfig() {
@@ -227,7 +230,7 @@ function CopyDirs() {
 function CloneRepo() {
     local DIR="$1"
 
-    [[ -z "${USERNAME}" && -z "${REPO_NAME}" ]] && {
+    [[ -z "${REMOTE_USERNAME}" && -z "${REPO_NAME}" ]] && {
         log error "No github username or repo name is given"
         exit 1
     }
@@ -241,15 +244,12 @@ function CloneRepo() {
 
     log debug "Getting dotfile repo from github"
     log info "Cloning your repository at: $DIR"
-    git clone "https://github.com/${USERNAME}/${REPO_NAME}.git" "${DIR}" && \
+    git clone "https://github.com/${REMOTE_USERNAME}/${REPO_NAME}.git" "${DIR}" && \
         log info "Repository clone at '${BLUE}$(ColorPath "${DIR}")${NC}'"
 }
 
 function PushToRepo() {
-    local force="$1"
-    local satisfied=""
-    local should_continue=""
-    local should_commit=""
+    local force_push=${1}
     local commit_template_file=""
 
     for file in ~/.git_commit_template_file ~/.gitmessage ~/.git_template; do
@@ -258,8 +258,8 @@ function PushToRepo() {
 
     [[ -z "${commit_template_file}" ]] && commit_template_file=<( printf "[tag] module: what changed\n\n" )
 
-    if [[ -z "${USERNAME}" ]]; then
-        log error "'USERNAME' is empty update your '$(ColorPath "${CONFIG_FILE}")'"
+    if [[ -z "${REMOTE_USERNAME}" ]]; then
+        log error "'REMOTE_USERNAME' is empty update your '$(ColorPath "${CONFIG_FILE}")'"
         return 1
     fi
     if [[ -z "${REPO_NAME}" ]]; then
@@ -279,26 +279,40 @@ function PushToRepo() {
     log info "Summary of staged changes"
     git diff --staged --stat
 
-    printf "%s: " "Are you saisfied with changes? (y|n)"; read -r satisfied
+    local is_satisfied=""
+    printf "%s: " "Are you saisfied with changes? (y|n)"; read -r is_satisfied
 
-    if [[ "${satisfied}" =~ ^(y|yes|Yes)$ ]]; then
+    if [[ "${is_satisfied}" =~ ^(y|yes|Yes)$ ]]; then
+        local should_commit=""
         printf "%s: " "Commit? (y|n)"; read -r should_commit
         [[ "${should_commit}" =~ ^(y|yes|Yes)$ ]] || return 1
         if git commit --template="${commit_template_file}"; then
             log info "Successfully commited the changes"
         else
              if ! git diff --quiet --staged && git diff --quiet --staged; then
-                 log error "Commit failed" && exit 1
+                 log error "Commit failed" && return 1
              fi
         fi
     else
         log info "Commit aborted"
+        local should_continue=""
         printf "%s: " "Continue to commit?"; read -r should_continue
-        [[ "${should_continue}" =~ ^(y|yes|Yes)$ ]] || exit 1
+        [[ "${should_continue}" =~ ^(y|yes|Yes)$ ]] || return 1
     fi
-    log info "Pushing changes to git@github.com:${USERNAME}/${REPO_NAME}.git"
-    git push "git@github.com:${USERNAME}/${REPO_NAME}.git" "$(git symbolic-ref --short HEAD)" "${force}" && \
-        log info "Successfully pushed your changes to github repository"
+
+    local -a git_flags=(
+        "git@github.com:${REMOTE_USERNAME}/${REPO_NAME}.git"
+        "$(git symbolic-ref --short HEAD)"
+    )
+
+    [[ $force_push -eq 1 ]] && git_flags+=( "--force" )
+
+    log info "Push (force) changes to git@github.com:${REMOTE_USERNAME}/${REPO_NAME}.git"
+    if git push "${git_flags[@]}"; then
+        log info "Successfully pushed your changes at 'git@github.com:${REMOTE_USERNAME}/${REPO_NAME}.git'"
+    else
+        log error "Failed to push your changes at 'git@github.com:${REMOTE_USERNAME}/${REPO_NAME}.git'"
+    fi
 }
 
 function Cleanup() {
@@ -310,7 +324,7 @@ function Usage() {
     "${HL}Sync and Backup dotfile${NC}" \
     "" \
     "Usage:" \
-    "  BackUp [options]" \
+    "  ${0##*/} [options]" \
     ""  \
     "Options:" \
     "  -h, --help            Show this help message and exit" \
@@ -321,110 +335,56 @@ function Usage() {
     "  -s, --show            Show the config file ($(ColorPath "${CONFIG_FILE}"))" \
     "  -g, --git-status      Show git status of your dotfile repo after backup" \
     "  -c DIR, --clone DIR   Clone your dotfile repo to specified DIR (local path)" \
-    "  -m MSG, --msg MSG     Commit message for git push" \
     "  -p, --push            Push changes to your remote GitHub repository" \
     "  --force               Force git push with --force flag" \
     ""  \
     "Description:" \
-    "  This script copies important config files and directories into a" \
+    "  This script copies important configuration files and directories into a" \
     "  local git repository (${BLUE}$(ColorPath "${GIT_DIR}")${NC}) for backup and version control." \
     "  Optionally can clone your dotfiles repo from remote, push changes, and see git status." \
     "" \
     "Your Remote repo info:" \
-    "  Username: ${BLUE}${USERNAME}${NC}" \
+    "  Username: ${BLUE}${REMOTE_USERNAME}${NC}" \
     "  Repository: ${BLUE}${REPO_NAME}${NC}"
 }
 
-trap Cleanup SIGINT SIGTERM
-
 function main() {
     # An array to hold all the given flags
-    local -a flagArr=("$@")
-
-    # Temporary variable
-    local -g MSG=""
+    local -a args=("$@")
 
     # 1 for git status 0 for no git status
     local git_status=0
 
-    # Toggle push or pull
+    # On off switches
     local -i should_push=0 should_clone=0
     local -i show_help=0 show_config=0
+    local -i force_push=0 should_edit_config=0
+
     # Clone directory
     local clone_dir=""
 
-    local force=""
-
-    for ((i=0;i<${#flagArr[@]};i++)); do
-        arg="${flagArr[$i]}"
+    local arg="" value=""
+    for ((i=0;i<${#args[@]};i++)); do
+        arg="${args[$i]}"
+        [[ "${args[$((i+1))]:-""}" && "${args[$((i+1))]:-""}" != -* ]] && \
+            value="${args[$((i+1))]:-""}" i=$((i+1))
+        if [[ "${arg}" == *=* ]]; then
+            IFS=$'=' read -r arg value <<< "${arg}"
+            [[ -n "${value}" ]] || \
+                { log error "'${arg}' requires a value"; return 1; }
+        fi
+        [[ "${arg}" == --* ]] && arg="${arg//--/-}"
         case "${arg}" in
-            -v|-*verbose|-*progress|verbose)
-                LOG_LEVEL=1
-                log debug "Verbose is set"
-                ;;
-            -l=*|-*log*=*|log*=*)
-                LOG_LEVEL=${arg#*=}
-                if [[ -z ${LOG_LEVEL} || ${LOG_LEVEL} == -* ]] || [[ ! ${LOG_LEVEL} =~ ^[0-9]+$ ]]; then
-                    LOG_LEVEL=1
-                elif [[ $LOG_LEVEL -gt 3 ]]; then
-                    log debug "LOG_LEVEL has no effect over integer ${LOG_LEVEL}"
-                fi
-                [[ $LOG_LEVEL -ge 3 ]] && log debug "Debugging enabled"
-                ;;
-            -l|-*log*|log*)
-                LOG_LEVEL=${flagArr[$(( i + 1 ))]:-1}
-
-                if [[ -z ${LOG_LEVEL} || ${LOG_LEVEL} == -* ]]; then
-                    LOG_LEVEL=1
-                elif [[ $LOG_LEVEL -gt 3 ]]; then
-                    log debug "LOG_LEVEL has no effect over integer ${LOG_LEVEL}"
-                fi
-                [[ $LOG_LEVEL -ge 3 ]] && log debug "Debugging enabled"
-                i=$(( i + 1 ))
-                ;;
-            -d-*debug|debug)
-                LOG_LEVEL=2
-                log debug "Debugging enabled"
-                ;;
-            -g|-*gs|-*git*stat*|git*stat*)
-                git_status=1
-                log debug "git_status is set"
-                ;;
-            -e|-*edit|edit)
-                EditConfig "${CONFIG_FILE}"
-                return 0
-                ;;
-            -s|-*show*|show*)
-                show_config=1
-                ;;
-            -c|--clone*|clone*)
-                clone_dir="${flagArr[$(( i + 1 ))]}"
-                [[ -n "${clone_dir}" ]] && {
-                    i=$(( i + 1 ))
-                }
-                should_clone=1
-                ;;
-            -c=*|-*clone*=*)
-                clone_dir="${arg#*=}"
-                should_clone=1
-                ;;
-            -m|-*msg)
-                MSG="${flagArr[$(( i + 1 ))]}"
-                [[ -n "${MSG}" ]] && {
-                    i=$(( i + 1 ))
-                }
-                should_clone=1
-                ;;
-            -p|-*push|push)
-                should_push=1
-                LOG_LEVEL=2
-                log debug "Backup will be pushed to github"
-                ;;
-            -*force)
-                force="--force"
-                log debug "Forcing push"
-                ;;
-            -h|-*help|help) show_help=1 ;;
+            -l|-log*)               LOG_LEVEL=${value}; [[ -z "${LOG_LEVEL}" ]] && LOG_LEVEL=1 ;;
+            -g|-gs|-git*status)     git_status=1 ;;
+            -e|-edit)               should_edit_config=1 ;;
+            -s|-show*)              show_config=1 ;;
+            -d|-debug)              LOG_LEVEL=2 ;;
+            -v|-verbose|-progress)  LOG_LEVEL=1 ;;
+            -c|--clone*)            clone_dir="${value}"; should_clone=1 ;;
+            -p|-push)               should_push=1 LOG_LEVEL=2 ;;
+            -force)                 force_push=1 ;;
+            -h|-help)               show_help=1 ;;
             *)
                 log error "Invalid flag: $arg"
                 return 1
@@ -432,12 +392,23 @@ function main() {
         esac
     done
 
+    trap Cleanup SIGINT SIGTERM
+
     mkdir -p "${CONFIG_FILE%/*}"
 
     SourceConfig "${CONFIG_FILE}"
 
+    log debug "Using GIT_DIR=$(ColorPath "${GIT_DIR}")"
+    log debug "Using git_status=$git_status"
+    log debug "Using LOG_LEVEL=$LOG_LEVEL"
+    log debug "Using SYNC_=$SYNC_"
+    [[ $LOG_LEVEL -eq 1 ]] && log debug "Verbose is set"
+    [[ $LOG_LEVEL -eq 2 ]] && log debug "Debugging enabled"
+    [[ $git_status -eq 1 ]] && log debug "git_status is set"
+
     [[ $show_help -eq 1 ]] && { Usage; return 0; }
     [[ $show_config -eq 1 ]] && { ShowConfig; return 0; }
+    [[ $should_edit_config -eq 1 ]] && { EditConfig "${CONFIG_FILE}"; return 0; }
 
     ValidatePaths COPY_FILES || return 1
     ValidateDirPaths COPY_DIRS || return 1
@@ -462,11 +433,6 @@ function main() {
             return 1
         fi
     fi
-
-    log debug "Using GIT_DIR=$(ColorPath "${GIT_DIR}")"
-    log debug "Using git_status=$git_status"
-    log debug "Using LOG_LEVEL=$LOG_LEVEL"
-    log debug "Using SYNC_=$SYNC_"
 
     # Start copying all the files to the destination
     for pair in "${COPY_FILES[@]}"; do
@@ -493,7 +459,10 @@ function main() {
     printf '\n' && log info "Dotfile directory: ${BLUE}$(ColorPath "${GIT_DIR}")${NC}\n"
 
     if [[ $should_push -eq 1 ]]; then
-        PushToRepo "${force}" || return 1
+        log debug "Backup will be pushed to github"
+
+        [[ $force_push -eq 1 ]] && log debug "Force push"
+        PushToRepo "${force_push}" || return 1
     else
         return 0
     fi
diff --git a/scripts/main/UdevSync b/scripts/main/UdevSync
--- a/scripts/main/UdevSync
+++ b/scripts/main/UdevSync
@@ -174,7 +174,7 @@ function CreateUdevSyncScript() {
         sudo mkdir -p "${script_path%/*}"
     fi
 
-    "${write[@]}" "${script_path}" > /dev/null << EOF
+    if ! "${write[@]}" "${script_path}" > /dev/null << EOF
 #!/usr/bin/env bash
 
 set -euo pipefail
@@ -402,16 +402,19 @@ function main() {
 main "\$@"
 
 EOF
-    [[ $? -eq 0 ]] || return 1
+    then
+        log error "Failed to install script"
+        return 1
+    fi
 
     if [[ $update_this_script -eq 1 ]]; then
         log info "Successfully updated '${script_path}'\n"
-    else
-        USER="${USER}"
-        sudo chown "${SUDO_USER:-${USER}}" "${script_path}"
-        sudo chmod 0755 "${script_path}"
-        log info "Successfully installed script at '${script_path}'\n"
+        return 0
     fi
+
+    sudo chown "${SUDO_USER:-${USER}}" "${script_path}"
+    sudo chmod 0755 "${script_path}"
+    log info "Successfully installed script at '${script_path}'\n"
 }
 
 function CreateSystemdService() {
@@ -440,7 +443,7 @@ function CreateSystemdService() {
         return 0
     fi
 
-"${write[@]}" "${systemd_service_file}" &> /dev/null << EOF
+    if "${write[@]}" "${systemd_service_file}" &> /dev/null << EOF
 [Unit]
 Description=Udev sync
 
@@ -454,7 +457,7 @@ WantedBy=
 
 EOF
 
-    if [[ $? -eq 0 ]]; then
+    then
         sudo systemctl --quiet daemon-reload
         log info "Custom systemd service installed and reloaded '${systemd_service_file}'\n"
     else
@@ -504,8 +507,9 @@ function CreateUdevRule() {
 
 function EditConfig() {
     local configFile="${1}"
-    local -n set_flag=${2}
-    local temp_configFile="$(mktemp -t "${configFile##*/}.XXXX")"
+    local -n update_script_ref=${2}
+    local temp_configFile=""
+    temp_configFile="$(mktemp -t "${configFile##*/}.XXXX")"
     [[ ! -s "${temp_configFile}" ]] || { log error "Could not create temp file"; return 1; }
 
     [[ ! -s "${configFile}" ]] && CreateNewUserConfig "${configFile}"
@@ -517,6 +521,7 @@ function EditConfig() {
         rm -f "${temp_configFile}"
         return 0
     fi
+    # shellcheck disable=SC1090
     source "${temp_configFile}"
     for var in ROOT_DIR ITEMS PARTITION_UUID UDEV_RULE_NAME \
         SHOULD_ARCHIVE ARCHIVE_NAME ARCHIVE_FORMAT SYSTEMD_SERVICE_NAME; do
@@ -524,6 +529,7 @@ function EditConfig() {
         if [[ ! -s "${temp_configFile}" ]]; then
             CreateNewUserConfig "${configFile}"
             cp "${configFile}" "${temp_configFile}"
+            # shellcheck disable=SC1090
             source "${temp_configFile}"
         else
             log error "'${var}' var is missing, discarding any changes you made"
@@ -532,13 +538,14 @@ function EditConfig() {
         fi
     done
     log info "New changes detected in configuration, regenerating script"
-    set_flag=1
+    # shellcheck disable=SC2034
+    update_script_ref=1
     mv "${temp_configFile}" "${configFile}"
     rm -f "${temp_configFile}"
 }
 
 function UpdateConfigVars() {
-    local -n update=$1
+    local -n update=${1}
     sed -i "s@.*${update[0]}.*@${update[0]}=${update[1]}@"
 }
 
@@ -554,12 +561,12 @@ function main() {
     local uuid="" root_dir="" archive_fmt="" archive_name=""
     local remove_pattern=""
     local systemd_service_name=""
+    # shellcheck disable=SC2034
     local -a apply_config_update=()
 
     # On-Off Flags
     local -i archive_flag=0 update_script=0
-    local -i should_cat_log=0 show_service_status=0
-    local -i is_script_installed=0
+    local -i show_service_status=0
 
     # Install flags
     local -i should_install_udev_rule=0  should_install_script=0
@@ -571,82 +578,45 @@ function main() {
     # Arg parsing
     local -i should_edit=0 show_help=0
     local -i i=0
-    while [[ $i -lt ${#args[@]} ]]; do
-        case "${args[$i]}" in
-            --edit*|edit*)
-                should_edit=1
-                ;;
-            --config*|config*)
-                should_edit=1
-                ;;
-            --*script*|--install*script*|install*script*|*script*)
-                should_install_script=1
-                ;;
-            --*rule*|--gen*rule*|install*rule*|gen*rule*|install*rule*|*rule*)
-                should_install_udev_rule=1
-                ;;
-            --service*|install*service*|service*|system*service*)
-                should_install_systemd_service=1
-                ;;
-            --all*|all*)
-                should_install_script=1
-                should_install_udev_rule=1
-                should_install_systemd_service=1
-                ;;
-            --purge*|--remove*|--disable*|purge*|remove*|disable*)
-                should_install_or_purge=0
-                ;;
-            --install*|install*|enable*)
-                should_install_or_purge=1
-                ;;
-            --update*|update*)
-                update_script=1
-                ;;
-            --uuid=*|uuid=*)
-                uuid="${args[$i]#*=}"
-                apply_config_update=( "PARTITION_UUID" "${uuid}" )
-                UpdateConfigVars apply_config_update
-                ;;
-            --uuid*|uuid*)
-                i=$((i+1))
-                [[ $i -lt ${#args[@]} ]] && uuid="${args[$i]}" || \
-                    { log error "--uuid requires value"; return 1; }
-                apply_config_update=( "PARTITION_UUID" "${uuid}" )
-                UpdateConfigVars apply_config_update
-                ;;
-            --log*|log*)
-                CheckLogs "${logfile}" $should_cat_log
-                return 0
-                ;;
-            --tail*|tail*)
-                FollowLog "${logfile}"
-                return 0
-                ;;
-            --follow*|follow*)
-                FollowLog "${logfile}"
-                return 0
-                ;;
-            --cat*log*|cat*log*)
-                should_cat_log=1
-                CheckLogs "${logfile}" $should_cat_log
-                return 0
-                ;;
-            --*status*|*status*)
-                show_service_status=1
-                ;;
-            -h|--help*|help*)
-                show_help=1
-                ;;
+
+    local arg="" value=""
+    for ((i=0;i<${#args[@]};i++)); do
+        arg="${args[$i]}"
+        [[ "${args[$((i+1))]:-""}" && "${args[$((i+1))]:-""}" != -* ]] && \
+            value="${args[$((i+1))]:-""}" i=$((i+1))
+        if [[ "${arg}" == *=* ]]; then
+            IFS=$'=' read -r arg value <<< "${arg}"
+            [[ -n "${value}" ]] || \
+                { log error "'${arg}' requires a value"; return 1; }
+        fi
+        [[ "${arg}" == --* ]] && arg="${arg//--/-}"
+        case "${arg}" in
+            -edit)                      should_edit=1                       ;;
+            -config*)                   should_edit=1                       ;;
+            -purge*|-remove*|-disable*) should_install_or_purge=0           ;;
+            -update*)                   update_script=1                     ;;
+            -show*status*)              show_service_status=1               ;;
+            -h|-help)                   show_help=1                         ;;
+            -install*script)            should_install_script=1             ;;
+            -gen*rule*|-install*rule*)  should_install_udev_rule=1          ;;
+            -install*service*)          should_install_systemd_service=1    ;;
+            -install*)                  should_install_or_purge=1           ;;
+            -log*)                      CheckLogs "${logfile}" 0; return 0  ;;
+            -cat*log*)                  CheckLogs "${logfile}" 1; return 0  ;;
+            -tail*|-follow*)            FollowLog "${logfile}"; return 0    ;;
+            -all*)                      should_install_script=1 \
+                                        should_install_udev_rule=1 \
+                                        should_install_systemd_service=1    ;;
+            -uuid*|uuid*)               uuid="${value}"; \
+                        apply_config_update=( "PARTITION_UUID" "${uuid}" ) \
+                            UpdateConfigVars apply_config_update            ;;
             *)
                 log error "Unknown arg: '${args[$i]}'"
                 Usage "${script_install_path}" >&2
                 return 1
                 ;;
         esac
-        i=$((i+1))
     done
-
-    DependencyChecks
 
     if [[ $show_help -eq 1 ]]; then
         if [[ $should_install_udev_rule -eq 1 ]]; then
@@ -658,12 +628,13 @@ function main() {
     fi
 
     if [[ $should_edit -eq 1 ]]; then
-        if EditConfig "${config_file}" update_script; then
-            [[ $update_script -eq 0 ]] && return $? || true
-        else
-            return 1
-        fi
+        EditConfig "${config_file}" update_script
+        # If not updaing script, exit
+        [[ $update_script -eq 0 ]] && return 0
     fi
+
+    # Check dependencies before doing anything
+    DependencyChecks
 
     # Source config (retry up to 3x if incomplete)
     local source_attempt=0 should_break=0
@@ -675,6 +646,7 @@ function main() {
             CreateNewUserConfig "${config_file}" || { log error "Failed to write '${config_file}'"; return 1; }
         fi
 
+        # shellcheck disable=SC1090
         if ! source "${config_file}"; then
             log warn "Failed to source config, regenerating config"
             CreateNewUserConfig "${config_file}" || { log error "Failed to write '${config_file}'"; return 1; }
@@ -688,6 +660,7 @@ function main() {
             local should_not_match="${3:-"_NONE_"}"
 
             if [[ -n "${ref2:-""}" && "${ref2:-""}" != "${should_not_match}" ]]; then
+                # shellcheck disable=SC2034
                 ref1="${ref2:-""}"
             else
                 log error "Invalid or empty var \$${!ref2}, update the config"
@@ -709,8 +682,6 @@ function main() {
         should_break=1
     done
 
-    [[ -s "${script_install_path}" ]] && is_script_installed=1 || true
-
     [[ $show_service_status -eq 1 ]] && { ShowServiceStatus "${systemd_service_name}"; return 0; }
 
     # Install/Purge Udev Rule
@@ -720,7 +691,7 @@ function main() {
     fi
 
     # Install/Purge or update Udev Sync Script
-    if [[ ($update_script -eq 1 && $is_script_installed -eq 1) ||  $should_install_script -eq 1 ]]; then
+    if [[ ($update_script -eq 1 && -s ${script_install_path}) ]] || [[ $should_install_script -eq 1 ]]; then
         CreateUdevSyncScript \
             ITEMS "${root_dir}" "${script_install_path}" \
             "${archive_fmt}" "${archive_name}" \
@@ -740,11 +711,11 @@ function main() {
     [[ -s "/etc/systemd/system/${systemd_service_name}@.service" ]] && service_ready=1
 
     [[ $rule_ready -eq 0 && $should_install_or_purge -eq 1 ]] && \
-        { log warn "Udev rules not ready, install service: ${0##*/} install rule"; }
+        { log warn "Udev rules not ready, install service: ${script_name} -install rule"; }
     [[ $script_ready -eq 0 && $should_install_or_purge -eq 1 ]] && \
-        { log warn "Sync Script not ready, install service: ${0##*/} install script"; }
+        { log warn "Sync Script not ready, install service: ${script_name} -install script"; }
     [[ $service_ready -eq 0 && $should_install_or_purge -eq 1 ]] && \
-        { log warn "Systemd services not ready, install service: ${0##*/} install service"; }
+        { log warn "Systemd services not ready, install service: ${script_name} -install service"; }
 
     return 0
 }
diff --git a/scripts/main/Vmctl b/scripts/main/Vmctl
--- a/scripts/main/Vmctl
+++ b/scripts/main/Vmctl
@@ -41,7 +41,7 @@ function Usage() {
         "-f, fullscreen"    "Enable fullscreen mode" \
         "-e, edit"          "Edit the profiles config file"
 
-    printf "\n${HL}Other flags:${NC}\n"
+    printf '%b\n' "\n${HL}Other flags:${NC}\n"
     printf "  ${MSG_COL}%-18b${NC} %b\n" \
         "create-image"      "Create new disk image" \
         "format"            "Specify the disk format when creating a new image" \
@@ -50,7 +50,7 @@ function Usage() {
         "comment"           "Provide a comment when creating a new profile" \
         "-h, help"          "Show this help message"
 
-    printf "\n${HL}Examples:${NC}\n"
+    printf '%b\n' "\n${HL}Examples:${NC}\n"
     printf "  %s\n     ${HL}%b${NC}\n" \
         "Start with disk only"          "${script_basename} my_profile" \
         "Boot with Disk + ISO"          "${script_basename} boot my_profile" \
@@ -60,10 +60,10 @@ function Usage() {
 }
 
 function load_profile() {
-    local profile_name="$1"
-    local -n disk_img_=$2
-    local -n iso_img_=$3
-    local -n disk_format_=$4
+    local profile_name="${1}"
+    local -n disk_img_=${2}
+    local -n iso_img_=${3}
+    local -n disk_format_=${4}
     local -n selected_profile=${profile_name}
 
     if ! declare -p "${profile_name}" 2> /dev/null | grep -q 'declare -a' ; then
@@ -73,14 +73,12 @@ function load_profile() {
 
     for n in "${selected_profile[@]}"; do
         [[ "${n}" != *=* ]] && { log error "invalid pair '${n}'"; return 1; }
-        IFS=$'=' read -r key value "${n}"
+        IFS=$'=' read -r key value <<< "${n}"
         case "${key}" in
-            img) disk_img_+=("${value}") ;;
+            img) disk_img_="${value}" ;;
             iso) iso_img_="${value}" ;;
         esac
     done
-    disk_img_="${selected_profile[0]}"
-    iso_img_="${selected_profile[1]:="No_ISO"}"
     disk_format_="${disk_img_##*.}"
 }
 
@@ -97,7 +95,7 @@ function ListProfiles() {
     local config_file="$1"
     local -a available_profiles=""
     [[ -f "${config_file}" ]] || return 1
-    log info "Available profiles in $(ColorPath "${config_dir}"):"
+    log info "Available profiles in $(ColorPath "${CONFIG_DIR}"):"
     mapfile -t available_profiles < <(grep -o '^[A-Za-z_]*=(' "${config_file}" | sed 's/=(//')
     for (( i=0; i < ${#available_profiles[@]}; i++ )); do
         printf '   %s. %b\n' "$((i+1))" "${available_profiles[$i]}"
@@ -105,11 +103,11 @@ function ListProfiles() {
 }
 
 function CreateDiskImg() {
-    local img="$1"
-    local format="$2"
-    local size="$3"
+    local img="${1}"
+    local format="${2}"
+    local size="${3}"
     [[ "${img}" == *.* ]] || img="${img}.${format}"
-    qemu-img create -f ${format:-"raw"} "${img}" "${size:-"20G"}"
+    qemu-img create -f "${format:-"raw"}" "${img}" "${size:-"20G"}"
     log info "Disk created:"
     printf '    %s %-4s = %s\n' \
         "Disk image:  "  ""  "${img}" \
@@ -176,8 +174,8 @@ function boot_VM() {
         "-display" "gtk,gl=on,show-menubar=off,zoom-to-fit=on"
         "-boot" "d"
         "-enable-kvm"
-        "-drive" "file="${disk_img// /\\}",media=disk,format="${format}",if=virtio"
-        "-drive" "file="${iso// /\\}",media=cdrom"
+        "-drive" "file=${disk_img// /\\},media=disk,format=${format},if=virtio"
+        "-drive" "file=${iso// /\\},media=cdrom"
     )
 
     [[ $full_scr -eq 1 ]] && qemu_flags_arr+=( "-full-screen" )
@@ -234,86 +232,109 @@ function start_VM() {
     qemu-system-x86_64 "${qemu_flags_arr[@]}" & disown
 }
 
+# Helper functions
+
+function set_value() {
+    local -n var_ref=${1}
+    local -n value_ref=${2}
+    [[ -n "${value_ref}" ]] || { log error "'${var_ref}' requires a value"; return 1; }
+    var_ref="${value_ref}"
+}
+
+function set_profile() {
+    local -n var_ref=${1}
+    local -n value_ref=${2}
+    [[ -n "${value_ref}" ]] || { log error "'${var_ref}' requires a value"; return 1; }
+    var_ref+=("${value_ref}")
+}
+
+
+function resolve_path() {
+    local file="${1}" profile="${2}"
+    if [[ "${file}" == */* ]]; then
+        printf '%s\n' "${file}"
+    else
+        printf '%s\n' "${CONFIG_DIR}/${profile}/${file}"
+    fi
+}
+
+function require() {
+    local var="${1:-""}" _type="${2:-""}" msg="${3:-""}"
+    [[ -n "${var}" ]] && return 0
+    if [[ -n "${msg}" ]]; then
+        log "${_type}" "${msg}"; return 1
+    else
+        return 1
+    fi
+}
+
+function require_file() {
+    local file="${1}" msg="${2}"
+    [[ -f "${file}" ]] || \
+        { log error "${msg}"; return 1; }
+}
+
 function main() {
-    # Flags
-    local -a arg_array=("$@")
+    local -a args=("$@")
 
     local disk_img="" iso_img="" disk_format=""
+    local -g CONFIG_DIR="${HOME}/.config/custom/vmctl"
+    local -a profile_names=()
     local -a requested_profiles=()
-    local -g config_dir="${HOME}/.config/custom/vmctl"
-    local config_file="${config_dir}/profiles" profile_name=""
-    local comment="" create_img=""
+    local config_file="${CONFIG_DIR}/profiles"
+    local comment="" new_image_path=""
 
     local -i boot=0 full_scr=0
     local -i ram="$(( $(awk '/MemTotal/ { print $2 }' /proc/meminfo) / 1640 ))"
     local -i should_create_profile=0 should_create_img=0
     local disk_size=""
 
-    [[ ${#arg_array[@]} -eq 0 ]] && {
+    [[ ${#args[@]} -eq 0 ]] && {
         Usage "${config_file}"
         return 0
     }
 
-    mkdir -p "${config_dir}"
+    mkdir -p "${CONFIG_DIR}"
 
-    if [[ -s "${config_file}" && -f "${config_file}" ]]; then
-        source "${config_file}"
-    else
-        log warn "No profile found. Creating a default"
-        if WriteProfile "${config_file}"; then
-            log info "New default profile created at '$(ColorPath "${config_file}")'"
-        fi
+    if ! require_file "${config_file}" "Config '${config_file}' not found"; then
+        WriteProfile "${config_file}"
     fi
 
-    set_value() {
-        local -n var_ref=${1}
-        local -n value_ref=${2}
-        [[ -n "${value_ref}" ]] || { log error "'${var_ref}' requires a value"; return 1; }
-        var_ref="${value_ref}"
-    }
+    # shellcheck disable=SC1090
+    source "${config_file}"
 
     # Parse args
-    for arg in "${arg_array[@]}"; do
+    local arg="" value=""
+    for ((i=0;i<${#args[@]};i++)); do
+        arg="${args[$i]}"
+        [[ "${args[$((i+1))]:-""}" && "${args[$((i+1))]:-""}" != -* ]] && \
+            value="${args[$((i+1))]:-""}" i=$((i+1))
         if [[ "${arg}" == *=* ]]; then
             IFS=$'=' read -r arg value <<< "${arg}"
-            [[ -n "${value}" ]] || { log error "'${arg}' requires a value"; return 1; }
+            [[ -n "${value}" ]] || \
+                { log error "'${arg}' requires a value"; return 1; }
         fi
+        [[ "${arg}" == --* ]] && arg="${arg//--/-}"
         case "${arg}" in
-            boot|-*boot) boot=1 ;;
-            image|-*image) set_value disk_img value ;;
-            iso|-*iso) set_value iso_img value ;;
-            ram|-*ram) set_value ram value ;;
-            comm*) set_value comment value ;;
-            for*) set_value disk_format value ;;
-            pro*|-*pro*) set_value profile_name value ;;
-            -f|-*full*|*full*) full_scr=1 ;;
-            -*l|list*|-*list*) ListProfiles "${config_file}" return 0 ;;
-            edit|-*edit) EditConfigFile "${config_file}" return 0 ;;
-            h|-h|-*help|help) Usage "${config_file}" return 0 ;;
-            create*im*|-*create*im*)
-                IFS=$',' read -r create_img disk_format disk_size <<< "${value}"
-
-                # Image file
-                [[ -n "${create_img}" ]] && should_create_img=1 || { log fatal "No image specified"; return 1; }
-
-                # Disk format
-                case "${disk_format}" in
-                    raw|qcow2) set_value disk_format value ;;
-                    *) log error "Unknown format" ;;
-                esac
-
-                if [[ -z "${disk_format}" ]]; then disk_format="${create_img##*.}"
-                else disk_format="${disk_format}"
-                fi
-
-                # Disk size
-                if [[ "${disk_size}" =~ ^[0-8]+(K|M|G)$ ]]; then
-                    disk_size="${disk_size}"
-                fi
+            -b|-boot)           boot=1                                      ;;
+            -f|-full*)          full_scr=1                                  ;;
+            -image|-*image)     set_value disk_img value                    ;;
+            -iso|-*iso)         set_value iso_img value                     ;;
+            -ram|-*ram)         set_value ram value                         ;;
+            -comm*)             set_value comment value                     ;;
+            -for*)              set_value disk_format value                 ;;
+            -p|-profile*)       set_profile profile_names value              ;;
+            -l|-list*)          ListProfiles "${config_file}"; return 0     ;;
+            -e|-edit*)          EditConfigFile "${config_file}"; return 0   ;;
+            -h|-help)           Usage "${config_file}"; return 0            ;;
+            -create*ima*)
+                IFS=$',' read -r new_image_path disk_format disk_size <<< "${value}"
+                require "${new_image_path}" error "No image specified" && should_new_image_path=1
+                require "${disk_format}" "" "" || disk_format="${new_image_path##*.}"
+                [[ "${disk_size}" =~ ^[0-8]+(K|M|G)$ ]] || { log error "size not in K|M|G suffix"; return 1; }
                 ;;
-            new*pro*|create*pro*|pro*|-*create*pro*|-*new*pro*)
-                set_value profile_name value
-                [[ -z "${profile_name}" ]] && log fatal "No profile specified"
+            -create*pro*|-new*pro*)
+                set_profile profile_names value
                 should_create_profile=1
                 ;;
             [A-Za-z_]*)
@@ -331,85 +352,82 @@ function main() {
         esac
     done
 
-    if [[ -n "${profile_name}" ]]; then
-        requested_profiles+=("${profile_name}")
+    if [[ ${#profile_names[@]} -eq 0 ]]; then
+        log error "No profile given"
+        return 1
     fi
 
-    if [[ $should_create_img -eq 1 ]]; then
-        [[ -z "${profile_name}" ]] && log fatal "No profile name specified"
-        [[ -z "${create_img}" ]] && log fatal "No disk image specified"
-        [[ -z "${disk_format}" ]] &&  log fatal "No disk format specified"
-        [[ -z "${disk_size}" || "${disk_size}" == "0" ]] && log fatal "No image size specified"
-        mkdir -p "${config_dir}/${profile_name}"
-        CreateDiskImg "${config_dir}/${profile_name}/${create_img}" "${disk_format}" "${disk_size}"
-        return 0
-    fi
-
-    if [[ $should_create_profile -eq 1 ]]; then
-        local temp_iso_img="" temp_create_img=""
-        if [[ -z "${iso_img}" ]]; then
-            log warn "No ISO image is given"
-            temp_iso_img=""
-        elif [[ "${iso_img}" != */* ]]; then
-            temp_iso_img="${config_dir}/${profile_name}/${iso_img}"
-        else
-            temp_iso_img="${iso_img}"
-        fi
-
-        if [[ -z "${disk_img}" ]]; then
-            log fatal "No disk image is given"
-        elif [[ "${disk_img}" != */* ]]; then
-            temp_iso_img="${config_dir}/${profile_name}/${disk_img}"
-        else
-            temp_iso_img="${iso_img}"
-        fi
-
-        if [[ "${config_dir}/${profile_name}/${create_img}" ]]; then
-            temp_create_img="${config_dir}/${profile_name}/${create_img}"
-        fi
-
-        WriteProfile "${config_file}" "${profile_name}" "${disk_img:-"${temp_create_img}"}" "${iso_img:-"${temp_iso_img}"}" "${comment}" || \
-            log warn "'${profile_name}' already exists"
-        [[ $? -eq 0 ]] && return 0 || return 1
-    fi
-
-    if [[ ${#requested_profiles[@]} -eq 0 ]]; then
-        [[ -n "${profile_name}" ]] || log fatal "No profile name was given"
-    fi
-
-    source "${config_file}"
+    for profile in "${profile_names[@]}"; do
+        IFS=',' read -r -a parts <<< "${profile}"
+        requested_profiles+=("${parts[@]}")
+    done
 
     for req_profile in "${requested_profiles[@]}"; do
 
-        [[ -z "${disk_format}" ]] && disk_format="${iso_img#*.}"
+        new_image_path="$(resolve_path "${new_image_path}" "${req_profile}")"
 
-        [[ -n ${iso_img} ]] && boot=1
-
-        if [[ -z "${disk_img}" || -z "${iso_img}" || -z "${disk_format}" ]]; then
-            load_profile "${req_profile}" disk_img iso_img disk_format
+        if [[ $should_create_img -eq 1 ]]; then
+            require "${req_profile}" fatal "No profile name specified"
+            require "${new_image_path}" fatal "No disk image specified"
+            require "${disk_format}" fatal "No disk format specified"
+            require "${disk_size}" fatal "No image size specified"
+            [[ "${disk_size}" == "0" ]] && log fatal "Invalid disk size"
+            mkdir -p "${CONFIG_DIR}/${req_profile}"
+            CreateDiskImg "${new_image_path}" "${disk_format}" "${disk_size}"
+            return 0
         fi
 
-        # Path checks for disk image
-        if [[ -z "${disk_img}" ]]; then
-            log fatal "No disk image given"
-        elif [[ ! -s "${disk_img}" || ! -f "${disk_img}" ]]; then
-            log fatal "Disk image '${BLUE}${disk_img}${NC}' does not exist; Update it\n"
+        if [[ $should_create_profile -eq 1 ]]; then
+            local temp_iso_img="" temp_create_img=""
+            require "${iso_img}" warn "No ISO image is given"
+            temp_iso_img="$(resolve_path "${iso_img}" "${req_profile}")"
+            require "${disk_img}" fatal "No disk image is given"
+            temp_iso_img="$(resolve_path "${disk_img}" "${req_profile}")"
+
+            WriteProfile \
+                "${config_file}" \
+                "${req_profile}" \
+                "${disk_img:-"${temp_create_img}"}" \
+                "${iso_img:-"${temp_iso_img}"}" \
+                "${comment}" || \
+                log warn "'${req_profile}' already exists"
+            return 0
         fi
 
+        if [[ ${#requested_profiles[@]} -eq 0 ]]; then
+            require "${req_profile}" fatal "No profile name was given"
+        fi
+
+        # shellcheck disable=SC1090
+        source "${config_file}"
+
+        load_profile "${req_profile}" disk_img iso_img disk_format
+
+        require "${disk_format}" "" "" || disk_format="${iso_img#*.}"
+        require "${disk_format}" error "Disk format not set"
+
+        require "${disk_img}" error "Disk image not set"
+        require_file "${disk_img}" error "Disk image path '${BLUE}${disk_img}${NC}' is invalid"
+
+        [[ $boot -eq 1 ]] && require "${iso_img}" error "Disk image not set"
+        [[ $boot -eq 1 ]] && require_file "${iso_img}" error "No ISO image given"
+
+        # Launch VM
         if [[ $boot -eq 1 ]]; then
-            # Path checks for iso image
-            if [[ -z "${iso_img}" ]]; then
-                log fatal "No ISO image given"
-            elif [[ ! -s "${iso_img}" || ! -f "${iso_img}" ]]; then
-                log fatal "ISO '${BLUE}${iso_img}${NC}' does not exist"
-            fi
-        fi
-
-        # Entry logic
-        if [[ $boot -eq 1 ]]; then
-            boot_VM "${disk_img}" "${iso_img}" "${disk_format}" $ram $full_scr "${req_profile}"
+            boot_VM \
+                "${disk_img}" \
+                "${iso_img}" \
+                "${disk_format}" \
+                $ram \
+                $full_scr \
+                "${req_profile}"
         else
-            start_VM "${disk_img}" "${disk_format}" $ram $full_scr "${req_profile}"
+            start_VM \
+                "${disk_img}" \
+                "${disk_format}" \
+                $ram \
+                $full_scr \
+                "${req_profile}"
         fi
     done
 }
