[bulk]: [all]: new scripts and changes

diff --git a/bootstrap/void/void_bootstrap b/bootstrap/void/void_bootstrap
--- a/bootstrap/void/void_bootstrap
+++ b/bootstrap/void/void_bootstrap
@@ -87,8 +87,7 @@ function Check_commands() {
     local -a commands=("${@}")
     for cmd in "${commands[@]}"; do
         if ! command -v "${cmd}" &> /dev/null; then
-            log error "'${cmd}' command not found"
-            return 1
+            log error "'${cmd}' command not found"; return 1
         fi
     done
 }
@@ -110,15 +109,15 @@ function Check_deps() {
 }
 
 function Move() {
-    local src="${1}"
-    local dest="${2}"
+    local src="${1}" dest="${2}"
+    local perms="${3:-0755}"
     local dest_dir="${dest%%/"${dest##*/}"}"
     sudo mkdir -p "${dest_dir}"
     sudo chown root:root "${dest_dir}"
     sudo mv "${src}" "${dest}"
     sudo chown root:root "${dest}"
     sudo rm -f "${src}" &> /dev/null || true
-    sudo chmod 0755 "${dest}"
+    sudo chmod "${perms}" "${dest}"
 }
 
 function Enable_service() {
@@ -314,7 +313,7 @@ EOF
 
 function SRC_build_nbfc_fancontrol() {
     local url="https://github.com/nbfc-linux/nbfc-linux.git"
-    local clone_dir="$HOME/repos/nbfc"
+    local clone_dir="$HOME/dev/repos/nbfc"
     local -a deps=( gcc libcurl-devel )
     Check_deps "${deps[@]}"
     # if binary already exists just create and enable service
@@ -323,17 +322,19 @@ function SRC_build_nbfc_fancontrol() {
             Enable_service nbfc-linux || return 1
         return 0
     fi
+
     mkdir -p "${clone_dir}"
-    if [[ -d "${clone_dir}" ]] && ! rmdir "${clone_dir}" &> /dev/null; then
-        read -r -n1 -p "'${clone_dir}' dir is not empty, remove it? y(es)|n(o), f(force) or q(uit): " yes_no
-        [[ "${yes_no}" =~ ^(Q|q)$ ]] && return 1
-        if [[ "${yes_no}" =~ ^(y|Y|f|F)$ ]]; then
-            rm -rf "${clone_dir}" && mkdir -p "${clone_dir}"
-        elif [[ "${yes_no}" =~ ^(N|n)$ ]]; then
-            clone_dir="${clone_dir}_$(od -An -tx1 -N1 /dev/urandom | sed 's/ //g')"
-            log info "New clone dir '${clone_dir}'"
+    if [[ -d "${clone_dir}" ]]; then
+        cd "${clone_dir}" || { log error "failed to chdir to ${clone_dir}"; return 1; }
+        if git status --short &>/dev/null; then
+            git pull --rebase --depth=1 "${url}"
+        else
+            git clone --depth=1 "${url}" "${clone_dir}"
         fi
+    else
+        git clone --depth=1 "${url}" "${clone_dir}"
     fi
+
     git clone --depth=1 "${url}" "${clone_dir}"
     cd "${clone_dir}" || log error "Failed to cd '${clone_dir}'"
     { ./autogen.sh && ./configure --prefix=/usr --sysconfdir=/etc && make && sudo make install; } || \
@@ -362,25 +363,76 @@ function Install_ActivityWatch() {
 
 function SRC_build_ly_loginmanager() {
     local url="https://codeberg.org/fairyglade/ly.git"
-    local clone_dir="$HOME/repos/ly"
+    local clone_dir="$HOME/dev/repos/ly"
 
-    local -a deps=( xorg pam-devel libxcb-devel )
-    Check_deps "${deps[@]}"
-    Check_commands zig
+    # checks
+    Check_deps xorg pam-devel libxcb-devel
+    Check_commands zig || return 1
 
+    # clone repo
     mkdir -p "${clone_dir}"
-    git clone --depth=1 "${url}" "${clone_dir}"
-    cd "${clone_dir}" || log error "Failed to cd '${clone_dir}'"
+    if [[ -d "${clone_dir}" ]]; then
+        cd "${clone_dir}" || { log error "failed to chdir to ${clone_dir}"; return 1; }
+        if git status --short &>/dev/null; then
+            git pull --rebase --depth=1 "${url}"
+        else
+            git clone --depth=1 "${url}" "${clone_dir}"
+        fi
+    else
+        git clone --depth=1 "${url}" "${clone_dir}"
+    fi
+
+    # build and install
+    cd "${clone_dir}" || log error "Failed to chdir to '${clone_dir}'"
     sudo zig build installexe -Dinit_system=runit || \
-        { log error "Failed to build ly"; cd - &> /dev/null; return 1; }
-    cd - &> /dev/null
+        { log error "Failed to build ly"; return 1; }
+
     # Enable ly service
     Enable_service ly
-    # Disable agetty on tty2
+
+    # Disable agetty/ngetty on tty2
     local service_dir="/var/service"
     [[ -L "/var/service" ]] || service_dir="/etc/runit/runsvdir/default/"
-    { sudo rm -f "${service_dir}" &> /dev/null && log info "Disabled agetty on tty2"; } || \
-        { log error "Failed to disable agetty on tty2"; return 1; }
+    cd "${service_dir}" || { log error "failed to chdir to ${service_dir}"; return 1; }
+    if [[ -L ./tty2 ]]; then
+        { sudo rm ./"tty2" && log info "Disabled agetty on tty2"; } || \
+            { log error "Failed to disable agetty on tty2"; return 1; }
+    elif sudo sv status ngetty &>/dev/null; then
+        local tmpfile
+        tmpfile="$(mktemp)"
+        if cat 1> "${tmpfile}" << EOF
+OPTS="tty1 tty3 tty4 tty5 tty6"
+EOF
+        then
+            Move "${tmpfile}" /etc/sv/ngetty/conf 0644
+        fi
+    fi
+}
+
+function Install_VTconsole_font() {
+    local service_name="vtconsole-font"
+    local tmpfile
+    tmpfile="$(mktemp)"
+    log info "Installing vtconsole-font"
+    cat 1> "${tmpfile}" << EOF
+#!/bin/sh
+
+CONFIG="/etc/vtconsole.conf"
+VTs="/dev/tty[0-9]"
+FONT="ter-v24b"
+
+[ -r "\${CONFIG}" ] && . "\${CONFIG}"
+
+for tty in \$VTs; do
+    [ -c "\${tty}" ] || continue
+    setfont -C "\${tty}" "\${FONT}"
+done
+
+exec chpst -b "vtconsole-font: applied" pause
+
+EOF
+    Move "${tmpfile}" /etc/sv/"${service_name}"/run
+    Enable_service "${service_name}"
 }
 
 function Install_Zram() {
@@ -478,9 +530,16 @@ EOF
     fi
 }
 
+function Install_limactl() {
+    local version=""
+    version="$(curl -fsSL https://api.github.com/repos/lima-vm/lima/releases/latest | jq -r .tag_name)"
+    curl -f#SLC- "https://github.com/lima-vm/lima/releases/download/${version}/lima-${version:1}-$(uname -s)-$(uname -m).tar.gz" | sudo tar Cxzvm "/usr/local/"
+    curl -f#SLC- "https://github.com/lima-vm/lima/releases/download/${version}/lima-additional-guestagents-${version:1}-$(uname -s)-$(uname -m).tar.gz" | sudo tar Cxzvm "/usr/local/"
+}
+
 function Neovim_setup() {
     Check_deps neovim nodejs
-    Check_commands npm node
+    Check_commands npm node || return 1
     local output_file="init.vim"
     local nvim_dir="/etc/xdg/nvim"
     local nvim_conf="${0%%/"${0##*/}"}/${output_file}"
@@ -517,14 +576,6 @@ function Install_graphics_tools() {
         linux-tools
     )
     XBPS_install "${MSG}" "${XBPSPkgs[@]}"
-}
-
-function Enable_mpv_mpris() {
-    # Enable mpris support for mpv
-    local library_path="/usr/lib/mpv-mpris"
-    local mpv_mpris_path="/etc/mpv/scripts/"
-    sudo mkdir -p "${mpv_mpris_path}"
-    sudo ln -sf "${library_path}"/mpris.so "${mpv_mpris_path}/"
 }
 
 function locale-gen() {
@@ -715,10 +766,17 @@ function Install_misc_tools() {
     )
 
     XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+
+    # enable services
     # Enable_service acpid
     Enable_service dbus
     Enable_service udevd
-    Enable_mpv_mpris
+
+    # Enable mpris support for mpv
+    local library_path="/usr/lib/mpv-mpris"
+    local mpv_mpris_path="/etc/mpv/scripts/"
+    sudo mkdir -p "${mpv_mpris_path}"
+    sudo ln -sf "${library_path}"/mpris.so "${mpv_mpris_path}/"
 }
 
 function Install_pentest_and_sec() {
@@ -768,11 +826,16 @@ function Install_utils() {
     local -a XBPSPkgs=(
         zip brightnessctl dust gdu tree procs firejail
         tmux rsync dnsmasq hostapd polkit elogind nftables
-        zsh zsh-syntax-highlighting openvpn zbar cronie zstd
+        zsh zsh-syntax-highlighting bash-completion openvpn zbar cronie zstd
         bat eza fzf jq lesspipe lsd micro ncdu neovim nodejs ripgrep
         fuse-sshfs lsof rsyslog plymouth man-db mlocate ngetty
         xdg-desktop-portal xdg-desktop-portal-wlr xdg-desktop-portal-gtk
-        chafa numactl fbterm frp cryptsetup
+        chafa numactl fbterm frp cryptsetup jless
+        filelight
+        keypunch fd
+        vmpk # virtual piano
+        spek-x sonic-visualiser # audio visualizers
+        cutter # a advanced debugger/disassembler
         man-pages-devel man-pages-posix # docs for C and POSIX
         libwebp-tools # cwewp
         ImageMagic NetworkManager network-manager-applet # Network Manager
@@ -833,7 +896,7 @@ function main() {
                 -f|-*force) force_reinstall=1 ;;
                 -i|-*install) install=1 ;;
                 -s|-*service) install_service_name="${value}" ;;
-                -*skip*update) update_system=0 ;;
+                --no[-_]update|--skip[-_]update) update_system=0 ;;
                 -h|--help) Usage; exit 0 ;;
                 *) log error "Unknown arg: '${arg}'" ;;
             esac
@@ -872,9 +935,11 @@ function main() {
             data*) DataBase_management ;;
             yt*) Install_yt_dlp ;;
             hypr*) Install_hyprland ;;
+            lima*) Install_limactl ;;
             activity*|parental*) Install_ActivityWatch ;;
             zram[0-9]*) Install_Zram "${arg}" ;;
             locale) locale-gen "en_US.UTF-8" ;;
+            *console[_-]font) Install_VTconsole_font ;;
             other|extras)
                 Install_extras
                 Install_productivity
@@ -896,6 +961,7 @@ function main() {
                 Install_AdGuardHome
                 Install_yt_dlp
                 Install_brew_pkg_manager
+                Install_VTconsole_font
                 SRC_build_ly_loginmanager
                 SRC_build_nbfc_fancontrol
                 ;;
diff --git a/scripts/main/Dotsync b/scripts/main/Dotsync
--- a/scripts/main/Dotsync
+++ b/scripts/main/Dotsync
@@ -9,7 +9,7 @@ CONFIG_FILE="${HOME}/.config/custom/${0##*/}/config"
 SYNC_="rsync"
 
 # LOG=0 ERROR=1 INFO=2 DEBUG=3
-LOG_LEVEL=1
+LOGLEVEL=1
 
 declare -a COPY_FILES=()
 declare -a COPY_DIRS=()
@@ -25,12 +25,21 @@ HL="\033[1m"
 function log() {
     local _type="${1}"; shift
     local _color="" _t=""
-    local -g info_color="\033[38;2;85;255;126m" \
-        warn_color="\033[38;2;255;170;10m" \
-        error_color="\033[38;2;244;29;31m" \
-        fatal_color="\033[5m\033[38;2;255;0;0m" \
-        other_color="\033[38;2;251;255;208m" \
-        nc="\033[0m"
+    local -i fallback_level=4
+
+    local -A level=(
+        [error]=1
+        [fatal]=1
+        [warn]=1
+        [info]=2
+        [debug]=3
+        [other]=4
+    )
+
+    local -g info_color="\033[38;2;85;255;126m" warn_color="\033[38;2;255;170;10m" \
+        error_color="\033[38;2;244;29;31m" fatal_color="\033[5m\033[38;2;255;0;0m" \
+        other_color="\033[38;2;251;255;208m" nc="\033[0m"
+
     case "${_type}" in
         info) _color="${info_color}" _t=" *" ;;
         warn) _color="${warn_color}" _t=" ^" ;;
@@ -39,6 +48,10 @@ function log() {
         fatal) _color="${fatal_color}" _t=" #" ;;
         *) _color="${other_color}" _t="" ;;
     esac
+
+    severity="${level[${_type}]:-${fallback_level}}"
+
+    (( LOGLEVEL >= severity )) || return 0
 
     printf "[%b%s%b%s]: %b\n" "${_color}" "${_type}" "${nc}" "${_t}" "${*}"
 }
@@ -74,17 +87,17 @@ COPY_FILES=(
 
 ### Copy directory to destination (repo) dir
 COPY_DIRS=(
-    #    src   |    dest   | [1|0] (1 = delete files from dest if not in src, 0 = do nothing)
-    "\${H}/.bin|\${GIT_DIR}/scripts|1"
-    "\${C}/sway|\${GIT_DIR}/sway|1"
-    "\${C}/hypr|\${GIT_DIR}/hyprland|1"
-    "\${C}/i3|\${GIT_DIR}/i3|1"
-    "\${C}/waybar|\${GIT_DIR}/waybar|1"
-    "\${C}/wofi|\${GIT_DIR}/wofi|1"
-    "\${C}/yazi|\${GIT_DIR}/yazi|1"
-    "\${C}/foot|\${GIT_DIR}/foot|1"
-    "\${C}/kitty|\${GIT_DIR}/kitty|1"
-    "\${C}/alacritty|\${GIT_DIR}/alacritty|1"
+    #    src   |    dest   | 1 = delete files from dest if not in src, 0 = do nothing | copy links
+    "\${H}/.bin|\${GIT_DIR}/scripts|1|1"
+    "\${C}/sway|\${GIT_DIR}/sway|1|0"
+    "\${C}/hypr|\${GIT_DIR}/hyprland|1|0"
+    "\${C}/i3|\${GIT_DIR}/i3|1|0"
+    "\${C}/waybar|\${GIT_DIR}/waybar|1|0"
+    "\${C}/wofi|\${GIT_DIR}/wofi|1|0"
+    "\${C}/yazi|\${GIT_DIR}/yazi|1|0"
+    "\${C}/foot|\${GIT_DIR}/foot|1|0"
+    "\${C}/kitty|\${GIT_DIR}/kitty|1|0"
+    "\${C}/alacritty|\${GIT_DIR}/alacritty|1|0"
 )
 
 # vim:filetype=iss
@@ -140,7 +153,8 @@ function SourceConfig() {
         CreateConfig "${config_file}"
     fi
     # shellcheck source=/dev/null
-    source "${config_file}" || { log error "Failed to source '${config_file}'"; return 1; }
+    source "${config_file}" || \
+        { log error "Failed to source '${config_file}'"; return 1; }
 }
 
 function EditConfig() {
@@ -178,12 +192,11 @@ function CopyFiles() {
     mkdir -p "${dest_%/*}"
 
     if [[ "$SYNC_" == "rsync" ]]; then
-        [[ $LOG_LEVEL -ge 2 ]] && cmd_flags+=( "--progress" )
+        [[ "$LOGLEVEL" -ge 2 ]] && cmd_flags+=( "--progress" )
         cmd_flags+=( "--archive" )
     elif [[ "$SYNC_" == "cp" ]]; then
-        [[ $LOG_LEVEL -ge 2 ]] && cmd_flags+=( "--verbose" )
-        cmd_flags+=( "--archive" )
-        cmd_flags+=( "--recursive" )
+        [[ "$LOGLEVEL" -ge 2 ]] && cmd_flags+=( "--verbose" )
+        cmd_flags+=( "--archive"  "--recursive" )
     fi
 
     if $SYNC_ "${cmd_flags[@]}" "${src_}" "${dest_}"; then
@@ -194,9 +207,10 @@ function CopyFiles() {
 }
 
 function CopyDirs() {
-    local src_="$1"
-    local dest_="$2"
-    local -i delete_flag=$3
+    local src_="${1}"
+    local dest_="${2}"
+    local -i delete_flag=${3}
+    local -i copy_links=${4}
     local -a cmd_flags=()
 
     if [[ ! -d "${src_}" ]]; then
@@ -212,11 +226,13 @@ function CopyDirs() {
     mkdir -p "${dest_}"
 
     if [[ "$SYNC_" == "rsync" ]]; then
-        [[ $LOG_LEVEL -ge 2 ]] && cmd_flags+=( "--progress" )
-        [[ $delete_flag -eq 1 ]] && cmd_flags+=( "--delete" )
+        [[ "$LOGLEVEL" -ge 2 ]] && cmd_flags+=( "--progress" )
+        [[ "$delete_flag" -eq 1 ]] && cmd_flags+=( "--delete" )
+        [[ "$copy_links" -eq 1 ]] && cmd_flags+=( "-L" )
         cmd_flags+=( "--archive" )
     elif [[ "$SYNC_" == "cp" ]]; then
-        [[ $LOG_LEVEL -ge 2 ]] && cmd_flags+=( "--verbose" )
+        [[ "$LOGLEVEL" -ge 2 ]] && cmd_flags+=( "--verbose" )
+        [[ "$copy_links" -eq 1 ]] && cmd_flags+=( "-L" )
         cmd_flags+=( "--archive" "--no-target-directory"  )
     fi
 
@@ -305,7 +321,7 @@ function PushToRepo() {
         "$(git symbolic-ref --short HEAD)"
     )
 
-    [[ $force_push -eq 1 ]] && git_flags+=( "--force" )
+    [[ "$force_push" -eq 1 ]] && git_flags+=( "--force" )
 
     log info "Push (force) changes to git@github.com:${REMOTE_USERNAME}/${REPO_NAME}.git"
     if git push "${git_flags[@]}"; then
@@ -328,9 +344,9 @@ function Usage() {
     ""  \
     "Options:" \
     "  -h, --help            Show this help message and exit" \
-    "  -v, --verbose         Set verbose output (LOG_LEVEL=1)" \
+    "  -v, --verbose         Set verbose output (LOGLEVEL=1)" \
     "  -l=N, --log=N         Set log level (0=none, 1=error, 2=info, 3=debug)" \
-    "  -d, --debug           Enable debug level logging (LOG_LEVEL=3)" \
+    "  -d, --debug           Enable debug level logging (LOGLEVEL=3)" \
     "  -e, --edit            Edit the config file ($(ColorPath "${CONFIG_FILE}"))" \
     "  -s, --show            Show the config file ($(ColorPath "${CONFIG_FILE}"))" \
     "  -g, --git-status      Show git status of your dotfile repo after backup" \
@@ -359,6 +375,7 @@ function main() {
     local -i should_push=0 should_clone=0
     local -i show_help=0 show_config=0
     local -i force_push=0 should_edit_config=0
+    local -i delete_flag=0 copy_links=0
 
     # Clone directory
     local clone_dir=""
@@ -375,14 +392,14 @@ function main() {
         fi
         [[ "${arg}" == --* ]] && arg="${arg//--/-}"
         case "${arg}" in
-            -l|-log*)               LOG_LEVEL=${value}; [[ -z "${LOG_LEVEL}" ]] && LOG_LEVEL=1 ;;
+            -l|-log*)               LOGLEVEL=${value}; [[ -z "${LOGLEVEL}" ]] && LOGLEVEL=1 ;;
             -g|-gs|-git*status)     git_status=1 ;;
             -e|-edit)               should_edit_config=1 ;;
             -s|-show*)              show_config=1 ;;
-            -d|-debug)              LOG_LEVEL=2 ;;
-            -v|-verbose|-progress)  LOG_LEVEL=1 ;;
+            -d|-debug)              LOGLEVEL=2 ;;
+            -v|-verbose|-progress)  LOGLEVEL=1 ;;
             -c|--clone*)            clone_dir="${value}"; should_clone=1 ;;
-            -p|-push)               should_push=1 LOG_LEVEL=2 ;;
+            -p|-push)               should_push=1 LOGLEVEL=2 ;;
             -force)                 force_push=1 ;;
             -h|-help)               show_help=1 ;;
             *)
@@ -400,15 +417,16 @@ function main() {
 
     log debug "Using GIT_DIR=$(ColorPath "${GIT_DIR}")"
     log debug "Using git_status=$git_status"
-    log debug "Using LOG_LEVEL=$LOG_LEVEL"
+    log debug "Using LOGLEVEL=$LOGLEVEL"
     log debug "Using SYNC_=$SYNC_"
-    [[ $LOG_LEVEL -eq 1 ]] && log debug "Verbose is set"
-    [[ $LOG_LEVEL -eq 2 ]] && log debug "Debugging enabled"
-    [[ $git_status -eq 1 ]] && log debug "git_status is set"
 
-    [[ $show_help -eq 1 ]] && { Usage; return 0; }
-    [[ $show_config -eq 1 ]] && { ShowConfig; return 0; }
-    [[ $should_edit_config -eq 1 ]] && { EditConfig "${CONFIG_FILE}"; return 0; }
+    [[ "$LOGLEVEL" -eq 1 ]] && log debug "Verbose is set"
+    [[ "$LOGLEVEL" -eq 2 ]] && log debug "Debugging enabled"
+    [[ "$git_status" -eq 1 ]] && log debug "git_status is set"
+
+    [[ "$show_help" -eq 1 ]] && { Usage; return 0; }
+    [[ "$show_config" -eq 1 ]] && { ShowConfig; return 0; }
+    [[ "$should_edit_config" -eq 1 ]] && { EditConfig "${CONFIG_FILE}"; return 0; }
 
     ValidatePaths COPY_FILES || return 1
     ValidateDirPaths COPY_DIRS || return 1
@@ -442,11 +460,11 @@ function main() {
 
     # Start copying directory content with selective deletion
     for dir_spec in "${COPY_DIRS[@]}"; do
-        IFS=$'|' read -r src dest delete_flag <<< "${dir_spec}"
-        CopyDirs "${src}" "${dest}" "${delete_flag}"
+        IFS=$'|' read -r src dest delete_flag copy_links <<< "${dir_spec}"
+        CopyDirs "${src}" "${dest}" "${delete_flag:-0}" "${copy_links:-0}"
     done
 
-    if [[ ${git_status} -eq 1 ]]; then
+    if [[ "$git_status" -eq 1 ]]; then
         printf '\n\n'
         cd "${GIT_DIR}"
         if git status &> /dev/null; then
@@ -458,10 +476,10 @@ function main() {
 
     printf '\n' && log info "Dotfile directory: ${BLUE}$(ColorPath "${GIT_DIR}")${NC}\n"
 
-    if [[ $should_push -eq 1 ]]; then
+    if [[ "$should_push" -eq 1 ]]; then
         log debug "Backup will be pushed to github"
 
-        [[ $force_push -eq 1 ]] && log debug "Force push"
+        [[ "$force_push" -eq 1 ]] && log debug "Force push"
         PushToRepo "${force_push}" || return 1
     else
         return 0
