[fix] scripts/main/RyzenProfile: Fix POSIX script profiles and init system checks, Update Usage()
[fix] templates_configs_scripts/code_templates/bash/arg_parser: Argument parsing, drop args without `-` prefix
[add] bootstrap/void/void_bootstrap: Add Install_Zram()
[refactor] scripts/main/MountSSH: Fixed argument parsing mess
[add] scripts/other/PlayMusic: `all` flag selects directory
[add] shell/shell_rc: Add GDB(), available_mem()

diff --git a/bootstrap/void/void_bootstrap b/bootstrap/void/void_bootstrap
--- a/bootstrap/void/void_bootstrap
+++ b/bootstrap/void/void_bootstrap
@@ -383,6 +383,101 @@ function SRC_build_ly_loginmanager() {
         { log error "Failed to disable agetty on tty2"; return 1; }
 }
 
+function Install_Zram() {
+    local service_name="${1}"
+    local tmpfile
+    log beautify "Installing zram swap runit service"
+    tmpfile="$(mktemp)"
+    if cat 1> "${tmpfile}" << EOF
+#!/usr/bin/sh
+
+## Create zram swap at boot
+
+exec 2>&1
+
+log() {
+    _type="\${1}"; shift 1
+    printf '[%s]: %s\\n' "\${_type}" "\${*}"
+}
+
+create_zram() {
+    _dev="\${1}"
+    _size="\${2}"
+    _algo="\${3}"
+
+    if [ -b "\${_dev}" ]; then
+        log info "zram '\${_dev}' already exists"
+        log info "Resetting '\${_dev}'"
+        swapoff "\${_dev}"
+        zramctl --reset "\${_dev}"
+    fi
+    sudo rmmod zram
+    modprobe zram num_devices=1 && sleep 0.3
+    zramctl --size="\${_size}" --algorithm="\${_algo}" "\${_dev}"
+}
+
+## Global variables
+ZRAM_DEV="" SIZE="" ALGO=""
+
+ZRAM_DEV="\$(readlink -f "\${0}")"
+ZRAM_DEV="\${ZRAM_DEV%/*}"
+ZRAM_DEV="\${ZRAM_DEV##*/}"
+ZRAM_DEV="/dev/\${ZRAM_DEV##*/}"
+
+SIZE="1G"
+ALGO="zstd"
+
+## Wait for meminfo
+while [ ! -f /proc/meminfo ]; do sleep 0.4; done
+
+## 1/3 rd of RAM given to zram for RAM based swaping
+SIZE=\$( awk '/MemTotal:/ { mb = int( ( (\$2)/(1024) ) / 3 ); printf "%.4dMib\n", mb } ' /proc/meminfo )
+
+[ -z "\${SIZE}" ] && { log error "Couldn't size for zram"; exit 1; }
+
+## Create a zram device
+create_zram "\${ZRAM_DEV}" "\${SIZE}" "\${ALGO}" || \\
+    { log error "Failed to create '\${ZRAM_DEV}'" ;exit 1; }
+
+{ [ -z "\${ZRAM_DEV}" ] || [ ! -b "\${ZRAM_DEV}" ]; } && \\
+    { log error "Failed to set zram (size=\${SIZE})"; exit 1; }
+
+## Create swap
+# Clear filesystem UUID and create swap
+mkswap -U clear "\${ZRAM_DEV}"
+# Enable swap
+swapon -o pri=100,discard=once,pages "\${ZRAM_DEV}"
+
+log info "zram swap enabled: \${ZRAM_DEV} (\${SIZE}, \${ALGO})\n"
+
+exec chpst -b "zram swap (DEV='\${ZRAM_DEV}', SIZE='\${SIZE}', ALGO=\${ALGO})" pause
+
+EOF
+    then
+        Move "${tmpfile}" /etc/sv/"${service_name}"/run
+        log info "Installed '${service_name}' (/etc/sv/${service_name}/run) runit service"
+    else
+        log error "Failed to install '${service_name}' (/etc/sv/${service_name}/run) runit service"
+        return 1
+    fi
+
+
+    tmpfile="$(mktemp)"
+    if cat 1> "${tmpfile}" << EOF
+#!/usr/bin/sh
+
+exec vlogger -t ${service_name} -p daemon
+
+EOF
+    then
+        Move "${tmpfile}" /etc/sv/"${service_name}"/log/run
+        log info "Installed '${service_name}' (/etc/sv/${service_name}/log/run) syslog service"
+        Enable_service "${service_name}"
+    else
+        log error "Failed to install '${service_name}' (/etc/sv/${service_name}/log/run) syslog service"
+    fi
+}
+
 function Neovim_setup() {
     Check_deps neovim nodejs
     Check_commands npm node
@@ -433,7 +528,7 @@ function Enable_mpv_mpris() {
 
 function locale-gen() {
     local locale="${1}"
-    read -r lang enc <<< "${locale}"
+    IFS=$'.' read -r lang enc <<< "${locale}"
     sudo localedef -i "${lang}" -f "${enc}" "${lang}.${enc}"
 }
 
@@ -659,6 +754,7 @@ function main() {
     local -a args=("${@}")
     local -g static_install_dir="/opt/static"
     local -g force_reinstall=0 install=0
+    local -i update_system=1
     local install_service_name=""
 
     local arg="" value=""
@@ -674,6 +770,7 @@ function main() {
                 -f|-*force) force_reinstall=1 ;;
                 -i|-*install) install=1 ;;
                 -s|-*service) install_service_name="${value}" ;;
+                -*skip*update) update_system=0 ;;
                 -h|--help) Usage; exit 0 ;;
                 *) log error "Unknown arg: '${arg}'" ;;
             esac
@@ -684,8 +781,10 @@ function main() {
     [[ -n "${install_service_name}" ]] && \
         { Install_service "${install_service_name}"; return 0; }
 
-    log beautify "Just a system update"
-    sudo xbps-install -Su
+    if [[ $update_system -eq 1 ]]; then
+        log beautify "Just a system update"
+        sudo xbps-install -Su
+    fi
 
     for ((i=0;i<${#args[@]};i++)); do
         arg="${args[$i]:-""}"
@@ -711,6 +810,7 @@ function main() {
             yt*) Install_yt_dlp ;;
             hypr*) Install_hyprland ;;
             activity*|parental*) Install_ActivityWatch ;;
+            zram[0-9]*) Install_Zram "${arg}" ;;
             locale) locale-gen "en_US.UTF-8" ;;
             other|extras)
                 Install_extras
@@ -728,6 +828,7 @@ function main() {
                 Install_term_filemanagers
                 Install_sway_setup
                 Install_misc_tools
+                Install_Zram "zram0"
                 Install_fonts_and_themes
                 Install_AdGuardHome
                 Install_yt_dlp
@@ -735,7 +836,7 @@ function main() {
                 SRC_build_ly_loginmanager
                 SRC_build_nbfc_fancontrol
                 ;;
-            [A-Za-z]*) log error "Unknown module: $arg" ;;
+            [A-Za-z]*) log error "Unknown module: ${arg}" ;;
         esac
     done
     log beautify "Complete!"
