[bulk] *: all

diff --git a/bootstrap/void/void_bootstrap b/bootstrap/void/void_bootstrap
--- a/bootstrap/void/void_bootstrap
+++ b/bootstrap/void/void_bootstrap
@@ -38,9 +38,9 @@ function XBPS_install() {
 
     log info "Packages will be installed: ${Install_Tool_list[*]}"
 
-    [[ ${#Install_Tool_list[@]} -eq 0 ]] && return 1
+    [[ "${#Install_Tool_list[@]}" -eq 0 ]] && return 1
 
-    [[ $force_reinstall -eq 1 ]] && xbps_cmd_args+=( -f )
+    [[ "$FORCE" -eq 1 ]] && xbps_cmd_args+=( -f )
 
     if sudo xbps-install "${xbps_cmd_args[@]}" "${Install_Tool_list[@]}"; then
         log info "Installed: '${Install_Tool_list[*]}'"
@@ -50,12 +50,12 @@ function XBPS_install() {
 }
 
 function Usage() {
-    local this_script="${0##*/}"
+    local n="${0##*/}"
     cat << EOF
     Usage:
         Usage of script:
-            ${this_script} -i,--install [PACKAGE_GROUP|all]
-            ${this_script} -i,--install -s,--service=SERVICE1,SERVICE2,...
+            ${n} -i,--install [PACKAGE_GROUP|all]
+            ${n} -i,--install -s,--service=SERVICE1,SERVICE2,...
         Available groups:
             graphics:           drivers: (nvidia,amd), Compute APIs: (vulkan,opengl)
             browsers:           qutebrowser, and opera
@@ -96,13 +96,14 @@ function Check_deps() {
     local -a pkgs=("$@")
     for pkg in "${pkgs[@]}"; do
         if ! xbps-query "${pkg}" &> /dev/null; then
-            log error "Failed to satisfy dependency '${pkg}'"
-            local yes_no
-            printf '%s' 'Should Install this package y(es)|n(o) or q(uit)?: '; read -r -n1 yes_no; printf '\n'
-            if [[ "${yes_no}" =~ ^(Y|y)$ ]]; then
-                sudo xbps-install -y "${pkg}"
-                continue
+            if [[ "${FORCE}" -eq 0 ]];then
+                log warn "Failed to satisfy dependency '${pkg}'"
+                local yes_no; printf '%s' "Install '${pkg}' package y(es)|n(o) or q(uit)?: "
+                read -r -n1 yes_no; printf '\n'
             fi
+            [[ "${yes_no}" =~ ^(Y|y)$ ]] || continue
+            sudo xbps-install -y "${pkg}"
+            continue
             return 1
         fi
     done
@@ -335,8 +336,7 @@ function SRC_build_nbfc_fancontrol() {
         git clone --depth=1 "${url}" "${clone_dir}"
     fi
 
-    git clone --depth=1 "${url}" "${clone_dir}"
-    cd "${clone_dir}" || log error "Failed to cd '${clone_dir}'"
+    cd "${clone_dir}" || log error "Failed to chdir to '${clone_dir}'"
     { ./autogen.sh && ./configure --prefix=/usr --sysconfdir=/etc && make && sudo make install; } || \
         { log error "Failed to build nbfc-linux"; cd - &> /dev/null; return 1; }
     cd - &> /dev/null
@@ -533,6 +533,7 @@ EOF
 function Install_limactl() {
     local version=""
     version="$(curl -fsSL https://api.github.com/repos/lima-vm/lima/releases/latest | jq -r .tag_name)"
+    sudo -v
     curl -f#SLC- "https://github.com/lima-vm/lima/releases/download/${version}/lima-${version:1}-$(uname -s)-$(uname -m).tar.gz" | sudo tar Cxzvm "/usr/local/"
     curl -f#SLC- "https://github.com/lima-vm/lima/releases/download/${version}/lima-additional-guestagents-${version:1}-$(uname -s)-$(uname -m).tar.gz" | sudo tar Cxzvm "/usr/local/"
 }
@@ -555,7 +556,7 @@ function Neovim_setup() {
 }
 
 function Install_graphics_tools() {
-    MSG="Video Graphics drivers (Nvidia + Amd)"
+    MSG="video graphics drivers (Nvidia + Amd)"
     local -a XBPSPkgs=(
         # Nvidia
         nvidia nvidia-firmware nvidia-vaapi-driver
@@ -575,12 +576,25 @@ function Install_graphics_tools() {
         vkBasalt
         linux-tools
     )
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
+}
+
+function Install_extra_repos() {
+    MSG="add extra repos"
+    local -a XBPSPkgs=(
+        void-repo-nonfree
+        void-repo-multilib
+        void-repo-multilib-nonfree
+    )
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function locale-gen() {
     local locale="${1}"
     IFS=$'.' read -r lang enc <<< "${locale}"
+    log info "setting up locale"
     sudo localedef -i "${lang}" -f "${enc}" "${lang}.${enc}"
 }
 
@@ -606,60 +620,65 @@ function Install_static_ffmpeg() {
 }
 
 function Install_browsers() {
-    MSG="Browsers"
+    MSG="web browsers"
     local -a XBPSPkgs=(
         qutebrowser python3-adblock
         opera tor
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function Install_terminals() {
-    MSG="Terminal emulators"
+    MSG="terminal emulators"
     local -a XBPSPkgs=(
-        alacritty foot
+        alacritty foot xterm
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function Install_Audio() {
-    MSG="Audio drivers"
+    MSG="audio drivers and utils"
     local -a XBPSPkgs=(
         alsa-firmware alsa-tools alsa-utils
         pipewire alsa-pipewire libjack-pipewire
-        pavucontrol cava
+        pavucontrol cava elisa mpd rtkit
         easyeffects calf lsp-plugins
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
     Enable_service rtkit
     Enable_pipewire_configs
 }
 
 function Install_monitors() {
-    MSG="Network monitoring tools"
+    MSG="network monitoring tools"
     local -a XBPSPkgs=(
         htop iftop btop nmon nvtop
-        powertop
+        powertop tlp
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
     Enable_service tlp
 }
 
 function DataBase_management() {
-    MSG="Utils"
+    MSG="database management tools"
     local -a XBPSPkgs=(
         postgresql mysql
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function Install_dev_tools() {
-    MSG="Utils"
+    MSG="dev build tools"
     local -a XBPSPkgs=(
         # development tools
         base-devel
@@ -672,30 +691,33 @@ function Install_dev_tools() {
         clang-tools-extra # for clangd
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function Install_term_filemanagers() {
-    MSG="Terminal File managers"
+    MSG="terminal file managers"
     local -a XBPSPkgs=(
         yazi vifm ranger nautilus dolphin konsole
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function Install_sway_setup() {
-    MSG="Install sway"
+    MSG="install sway"
     local -a XBPSPkgs=(
         sway swayidle swaylock xinit swww
         wayland xorg-server-xwayland xorg-server
         Waybar grim slurp wl-clipboard wf-recorder
         fuzzel autotiling okular
-        hyprlock
+        # hyprlock
         socat # unix socket
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function Install_hyprland() {
@@ -706,14 +728,15 @@ function Install_hyprland() {
     printf '%s\n' "${repo_url}" | sudo tee "${hyprland_repo}" &> /dev/null
     log info "Updating and adding hyprland repo"
     sudo xbps-install -S
-    MSG="Install hyprland"
+    MSG="hyprland"
     local -a XBPSPkgs=(
         hyprland hyprland-qtutils
         hyprland-qt-support hyprland-protocols
         xdg-desktop-portal-hyprland swww
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function Install_fonts_and_themes() {
@@ -724,17 +747,19 @@ function Install_fonts_and_themes() {
         qt6ct breeze-gtk breeze-qt6 # theme
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function Install_productivity() {
-    MSG="Extras"
+    MSG="graphics productivity"
     local -a XBPSPkgs=(
         blender krita gimp libreoffice-base
         kdenlive obs sublime-text4
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function Install_QEMU() {
@@ -744,11 +769,12 @@ function Install_QEMU() {
         qemu-img
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function Install_misc_tools() {
-    MSG="Miscellaneous Tools"
+    MSG="miscellaneous tools"
     local -a XBPSPkgs=(
         apache nginx
         acpid dhclient inxi
@@ -756,6 +782,7 @@ function Install_misc_tools() {
         xorg-server xorg-server-xwayland
         feh imv mpv mpv-mpris vlc
         wlr-randr pastel
+        kclock
         guvcview
         shellcheck
         vsv sv-helper # runit helpers
@@ -765,7 +792,8 @@ function Install_misc_tools() {
         net-tools
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 
     # enable services
     # Enable_service acpid
@@ -780,24 +808,26 @@ function Install_misc_tools() {
 }
 
 function Install_pentest_and_sec() {
-    MSG="Utils"
+    MSG="pentest and security utils"
     local -a XBPSPkgs=(
         nmap metasploit hydra john sqlmap
         nikto dirb gobuster ffuf
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 }
 
 function Install_Greeter() {
-    MSG="Utils"
+    MSG="greeter"
     local -a XBPSPkgs=(
         greetd # greeter daemon
         tuigreet # TUI UI
         fbterm
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 
     # greetd + tuigreet setup
 
@@ -817,36 +847,40 @@ user = "_greeter"
 EOF
 
     # Enable_service greetd
-    log info "Enable greetd 'sudo ln -s /etc/sv/greetd /var/service/'"
-
+    log info "to enable greetd: sudo ln -s /etc/sv/greetd /var/service/"
 }
 
 function Install_utils() {
-    MSG="Utils"
+    MSG="necessary utils"
     local -a XBPSPkgs=(
         zip brightnessctl dust gdu tree procs firejail
-        tmux rsync dnsmasq hostapd polkit elogind nftables
+        tmux tmate rsync dnsmasq hostapd polkit elogind nftables
         zsh zsh-syntax-highlighting bash-completion openvpn zbar cronie zstd
         bat eza fzf jq lesspipe lsd micro ncdu neovim nodejs ripgrep
         fuse-sshfs lsof rsyslog plymouth man-db mlocate ngetty
         xdg-desktop-portal xdg-desktop-portal-wlr xdg-desktop-portal-gtk
         chafa numactl fbterm frp cryptsetup jless
-        filelight
+        filelight 7zip
         keypunch fd
         vmpk # virtual piano
         spek-x sonic-visualiser # audio visualizers
         cutter # a advanced debugger/disassembler
         man-pages-devel man-pages-posix # docs for C and POSIX
         libwebp-tools # cwewp
-        ImageMagic NetworkManager network-manager-applet # Network Manager
+        ImageMagick NetworkManager network-manager-applet # Network Manager
         wireless_tools # for iwlist
         tldr # simple summary of commands
         bind-utils # Dig
         chrony # time
         mako # Notification daemon
+        exfatprogs exfat-utils # exfat utils
+        e2fsprogs # ext2/ext3/ext4 (default linux)
+        ntfs-3g   # ntfs support
+        dosfstools # fat32
     )
 
-    XBPS_install "${MSG}" "${XBPSPkgs[@]}"
+    XBPS_install "${MSG}" "${XBPSPkgs[@]}" || \
+        { log error "failed to install '${MSG}' packages"; exit 1; }
 
     sudo touch /etc/nftables.conf
     Enable_service NetworkManager
@@ -879,7 +913,7 @@ function Install_service() {
 function main() {
     local -a args=("${@}")
     local -g static_install_dir="/opt/static"
-    local -g force_reinstall=0 install=0
+    local -g install=0
     local -i update_system=1
     local install_service_name=""
 
@@ -893,7 +927,7 @@ function main() {
         fi
         if [[ "${arg}" == -* ]]; then
             case "${arg}" in
-                -f|-*force) force_reinstall=1 ;;
+                -f|-*force) FORCE=1 ;;
                 -i|-*install) install=1 ;;
                 -s|-*service) install_service_name="${value}" ;;
                 --no[-_]update|--skip[-_]update) update_system=0 ;;
@@ -907,8 +941,8 @@ function main() {
     [[ -n "${install_service_name}" ]] && \
         { Install_service "${install_service_name}"; return 0; }
 
-    if [[ $update_system -eq 1 ]]; then
-        log beautify "Just a system update"
+    if [[ "$update_system" -eq 1 ]]; then
+        log beautify "system update"
         sudo xbps-install -Su
     fi
 
@@ -929,7 +963,7 @@ function main() {
             sway) Install_sway_setup ;;
             misc) Install_misc_tools ;;
             nvim|neovim) Neovim_setup ;;
-            *brew) Install_brew_pkg_manager ;;
+	        *brew) Install_brew_pkg_manager ;;
             dev*) Install_dev_tools ;;
             prod*) Install_productivity ;;
             data*) DataBase_management ;;
@@ -946,6 +980,7 @@ function main() {
                 Install_hyprland
                 ;;
             all|essential*)
+                Install_extra_repos
                 Install_graphics_tools
                 Install_browsers
                 Install_terminals
@@ -960,9 +995,9 @@ function main() {
                 Install_fonts_and_themes
                 Install_AdGuardHome
                 Install_yt_dlp
-                Install_brew_pkg_manager
+                # Install_brew_pkg_manager
                 Install_VTconsole_font
-                SRC_build_ly_loginmanager
+                # SRC_build_ly_loginmanager
                 SRC_build_nbfc_fancontrol
                 ;;
             [A-Za-z]*) log error "Unknown module: ${arg}" ;;
diff --git a/shell/bashrc b/shell/bashrc
--- a/shell/bashrc
+++ b/shell/bashrc
@@ -1,58 +1,21 @@
 # If not running interactively, don't do anything
 [[ $- != *i* ]] && return
 
-#!/bin/bash
+source "$HOME/.cargo/env" 2> /dev/null
 
-# [[ Debian ]]
-# || User@Host ~ $ ||
-# PS1="\[\033[1m\]\[\033[38;2;80;24;230m\]||\[\033[0m\] \[\033[1m\]\[\033[3m\]\[\033[1;32m\]\$(whoami)\[\e[0m\]@\[\033[1m\]\[\033[3m\]\[\033[38;2;140;10;160m\]\$(hostname)\[\033[0m\]\[\e[m\] \[\e[0;36m\]\w\[\e[m\] $ \[\033[1m\]\[\033[38;2;80;24;230m\]||\[\033[0m\] "
-# echo
+source "${HOME}/.shell_rc" && main
 
-# [[ User@Host ~ $ ]]
-# PROMPT="%B%F{cyan}[[%b %B%F{#04ff5f}%n%b%F{white}%F{grey}%B@%b%B%F{#4A8DAF}%m%b %B%F{cyan}%~%b%F{white} $ %B%F{cyan}]]%b%f "
-
-
-# [[ Arch ]]
-
-# || User@Host ~ $ ||
-# PS1="\[\033[1m\]\[\033[38;2;80;24;230m\]||\[\033[0m\]\[\033[1m\]\[\033[3m\]\[\033[1;32m\]\$(whoami)\[\e[0m\]@\[\033[1m\]\[\033[3m\]\[\033[38;2;140;10;160m\]\$(hostname)\[\033[0m\]\[\e[m\] \[\e[0;36m\]\w\[\e[m\] $ \[\033[1m\033[38;2;80;24;230m\]||\[\033[0m\] "
-
-
-[[ $- != *i* ]] && return
-
-light_green="\[\033[38;2;163;240;96m\]"
-host_color="\[\033[38;2;231;245;180m\]"
-dir_color="\[\033[38;2;89;159;240m\]"
-branch_col="\[\033[38;2;129;137;223m\]"
-hl="\[\033[1m\]"
-nc="\[\033[0m\]"
-
-opening_bracket="${light_green}[[${nc}"
-closing_bracket="${light_green}]]${nc}"
-username="${light_green}\u${nc}"
-hostname="${host_color}\h${nc}"
-workingdirectory="${dir_color}\w${nc}"
-
-
-function show_current_git_branch() {
-    local blue="\[\033[38;2;0;200;200m\]"
-    local branch="$(git symbolic-ref --short HEAD 2> /dev/null)"
-    if [[ -n "${branch}" ]]; then
-        echo "${blue}(${nc}${branch_col}\[${branch}\]${nc}${blue})${nc} "
-    else
-        echo ""
-    fi
+function CD() {
+    local dir="${1:-}"
+    [[ -d "${dir}" ]] || { printf '[info]: %s\n' "Directory doesn't exist '${dir}'"; return 1; }
+    cd "${dir}" || printf '%b\n' "failed to chdir ${dir}"
 }
 
-# Custom Bash prompt by me — for color-coded, Git-aware shell
-
-PROMPT_COMMAND='PS1="${opening_bracket} ${username}@${hostname}:${workingdirectory} ${closing_bracket} $ $(show_current_git_branch)"'
-
-source "$HOME/.cargo/env" 2> /dev/null
-if source ${HOME}/.shell_rc 2> /dev/null; then
-    SetPath
-    SSH_Agent
-fi
+alias dotfiles="CD ~/dev/projects/repos/dotfiles"
+alias server="CD /srv/www/nginx"
+alias CPP="CD ~/other/Garage/C_PlusPlus/incompleted_souls.dir"
+alias C="CD ~/other/Garage/C_Lang"
+alias weather="curl wttr.in/24.5800,80.8369"
 
 [[ "$(tty)" == "/dev/tty"* ]] && setfont ter-732b
 
@@ -60,4 +23,6 @@ if [[ "$(tty)" == "/dev/tty"* ]]; then
     tput clear
     printf '\033]P01e1e2e\033]P1f38ba8\033]P2a6e3a1\033]P3f9e2af\033]P4fab387\033]P5f5c2e7\033]P6cba6f7\033]P7cdd6f4\033]P845475a\033]P9f38ba8\033]PAa6e3a1\033]PBf9e2af\033]PCfab387\033]PDf5c2e7\033]PEcba6f7\033]PFffffff'
 fi
+
+unset HISTFILE
 
diff --git a/sway/scripts/WaybarCava b/sway/scripts/WaybarCava
--- a/sway/scripts/WaybarCava
+++ b/sway/scripts/WaybarCava
@@ -3,17 +3,19 @@
 builtin set -euo pipefail
 
 LOGGING=0
+PROGRAM_NAME="${0##*/}"
+WORK_DIR="${XDG_RUNTIME_DIR:-/run/user/${UID:-$(id -u)}}/waybar/${PROGRAM_NAME}"
 
 # logger
 function log() {
     local type_="${1}"; shift
     [[ $LOGGING -eq 1 ]] && printf '[%s]: %s\n' "${type_}" "${*}" 1>&2
-    printf '[%s]: %b\n' "${type_}" "${*}" &>> "${work_dir}/waybar_.log"
+    printf '[%s]: %b\n' "${type_}" "${*}" &>> "${WORK_DIR}/waybar_.log"
 }
 
 function KILL_child_processes() {
     { pgrep -f ".*${0}" | grep -v "^$$" | xargs -r kill -SIGINT; } 2>/dev/null || true
-    { pkill -f "cava -p ${work_dir}/cava_visualizer_X_.*.fifo.*"; } 2>/dev/null || true
+    { pkill -f "cava -p ${WORK_DIR}/cava_visualizer_X_.*.fifo.*"; } 2>/dev/null || true
 }
 
 # write a fresh configuration for cava
@@ -72,8 +74,10 @@ function CleanUP() {
     local config="${2:-""}"
     local -n ref_pids=${3}
 
-    [[ -p "${pipe}" ]] && { rm -f "${pipe}" || log error "Failed to clean pipe '${pipe}'"; }
-    [[ -f "${config}" ]] && { rm -f "${config}" || log error "Failed to clean config '${config}'"; }
+    [[ -p "${pipe}" ]] && { rm -f "${pipe}" || \
+        log error "Failed to clean pipe '${pipe}'"; }
+    [[ -f "${config}" ]] && { rm -f "${config}" || \
+        log error "Failed to clean config '${config}'"; }
 
     for pid in "${ref_pids[@]}"; do
         if ps -p "${pid}" &> /dev/null; then
@@ -141,15 +145,14 @@ function ToggleBar() {
 
 function main() {
     local -a args=("${@}")
-    # global vars
-    local -g work_dir="/tmp/waybar/${0##*/}"
-    local tmp
-    # a temporary file for uniqueness
-    tmp="${work_dir}/cava_visualizer_X_$(hexdump -n2 -ve '/1 "%02x"' /dev/urandom).fifo"
+    local fifo_pipe=""
+    # a unique fifo pipe
+    fifo_pipe="${WORK_DIR}/cava_visualizer_X_$(hexdump -n2 -v --format '"%x"' /dev/urandom).fifo" || \
+        log error "command failed to run "
     # create cava config
-    local config_file="${tmp}_config"
+    local config_file="${fifo_pipe}_config"
     # output Pipe
-    local pipe="${tmp}"
+    local pipe="${fifo_pipe}"
     # ASCII characters
     local idle_cava_bar=""
     # glyph characters
@@ -162,7 +165,7 @@ function main() {
     local -i framerate=36
     # change the length of cava visualizer
     local -i bar_len=4
-    # bar style (1rd is default)
+    # bar style (1st is default)
     local -i use_bar_num=1
 
     local -a pids=()
@@ -179,7 +182,10 @@ function main() {
         esac
     done
 
-    mkdir -p "${work_dir}"
+    mkdir -p "${WORK_DIR}" || \
+        { log error "failed to create directory '${WORK_DIR}'"; return 1; }
+    chmod 0700 "${WORK_DIR}" || \
+        { log error "failed to change permissions of the directory '${WORK_DIR}'"; return 1; }
 
     KILL_child_processes
 
@@ -191,8 +197,8 @@ function main() {
 
     log info "bar num: ${use_bar_num}"
     log info "framerate: ${framerate}"
-    log info "work dir: ${work_dir}"
-    log info "log file: ${work_dir}/waybar_.log"
+    log info "work dir: ${WORK_DIR}"
+    log info "log file: ${WORK_DIR}/waybar_.log"
     log info "config file: ${config_file}"
     log info "pipe: ${pipe}"
     log info "noise level: ${noise_level}"
